/**
 * Curated question pools.
 *
 * Hand-written, and therefore the part of the bank that carries the usual risk
 * of authored trivia: everything here wants a human accuracy pass before real
 * money rides on it. The derived questions in derived*.ts read their answers
 * out of a reference table instead, which is why there are far more of those.
 *
 * Answer is written at index 0 for legibility; the builder shuffles.
 */
import type { Curated } from './types';

export const CURATED: Record<string, Curated[]> = {
  "Biology": [
  ["easy", "What is the powerhouse of the cell?", ["The mitochondrion", "The nucleus", "The ribosome", "The lysosome"], 0],
  ["easy", "How many chambers does a human heart have?", ["Four", "Two", "Three", "Six"], 0],
  ["easy", "What gas do plants take in for photosynthesis?", ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], 0],
  ["easy", "What is the largest organ in the human body?", ["The skin", "The liver", "The brain", "The lungs"], 0],
  ["easy", "Which blood cells carry oxygen?", ["Red blood cells", "White blood cells", "Platelets", "Plasma cells"], 0],
  ["easy", "How many bones are in an adult human body?", ["206", "300", "150", "250"], 0],
  ["easy", "Which organ produces insulin?", ["The pancreas", "The liver", "The kidney", "The spleen"], 0],
  ["easy", "What is the basic unit of life?", ["The cell", "The atom", "The molecule", "The tissue"], 0],
  ["easy", "Which animal group do frogs belong to?", ["Amphibians", "Reptiles", "Fish", "Mammals"], 0],
  ["easy", "What pigment makes plants green?", ["Chlorophyll", "Carotene", "Melanin", "Haemoglobin"], 0],
  ["easy", "Which part of a plant absorbs water?", ["The roots", "The leaves", "The stem", "The flower"], 0],
  ["easy", "How many legs does an insect have?", ["Six", "Eight", "Four", "Ten"], 0],
  ["easy", "What is the body's largest artery?", ["The aorta", "The carotid", "The femoral", "The pulmonary artery"], 0],
  ["easy", "Which sense organ detects light?", ["The eye", "The ear", "The nose", "The tongue"], 0],
  ["easy", "What do we call animals that eat only plants?", ["Herbivores", "Carnivores", "Omnivores", "Detritivores"], 0],
  ["easy", "Which vitamin does skin make from sunlight?", ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin K"], 0],
  ["easy", "Which organ filters waste from the blood?", ["The kidney", "The heart", "The lung", "The stomach"], 0],
  ["easy", "What turns a caterpillar into a butterfly?", ["Metamorphosis", "Photosynthesis", "Mitosis", "Osmosis"], 0],
  ["easy", "What is the study of living things called?", ["Biology", "Geology", "Chemistry", "Astronomy"], 0],
  ["easy", "Which animal is the largest living mammal?", ["The blue whale", "The African elephant", "The sperm whale", "The giraffe"], 0],
  ["easy", "How many hearts does an octopus have?", ["Three", "One", "Two", "Four"], 0],
  ["easy", "Which body system includes the brain and nerves?", ["The nervous system", "The digestive system", "The endocrine system", "The lymphatic system"], 0],
  ["easy", "What do bees collect to make honey?", ["Nectar", "Pollen", "Sap", "Dew"], 0],
  ["easy", "Which blood type is called the universal donor?", ["O negative", "AB positive", "A positive", "B negative"], 0],
  ["easy", "What is a group of lions called?", ["A pride", "A pack", "A herd", "A flock"], 0],
  ["easy", "Which sea creature has eight arms?", ["The octopus", "The squid", "The jellyfish", "The starfish"], 0],
  ["easy", "What do tadpoles grow into?", ["Frogs", "Fish", "Snakes", "Newts"], 0],
  ["easy", "Which organ pumps blood around the body?", ["The heart", "The lung", "The liver", "The brain"], 0],
  ["easy", "What is the hardest substance in the human body?", ["Tooth enamel", "Bone", "Cartilage", "Keratin"], 0],
  ["easy", "Which animal is known for changing colour to blend in?", ["The chameleon", "The gecko", "The iguana", "The skink"], 0],
  ["medium", "How many pairs of chromosomes does a human normally have?", ["23", "46", "22", "24"], 0],
  ["medium", "Which molecule carries oxygen in red blood cells?", ["Haemoglobin", "Myoglobin", "Albumin", "Keratin"], 0],
  ["medium", "Which cell division produces gametes?", ["Meiosis", "Mitosis", "Binary fission", "Budding"], 0],
  ["medium", "Which organelle builds proteins?", ["The ribosome", "The Golgi apparatus", "The vacuole", "The centriole"], 0],
  ["medium", "What is the longest bone in the human body?", ["The femur", "The tibia", "The humerus", "The fibula"], 0],
  ["medium", "Which kingdom do mushrooms belong to?", ["Fungi", "Plantae", "Animalia", "Protista"], 0],
  ["medium", "What is the term for an animal active at night?", ["Nocturnal", "Diurnal", "Crepuscular", "Hibernal"], 0],
  ["medium", "Which brain region controls balance and coordination?", ["The cerebellum", "The cerebrum", "The medulla", "The hypothalamus"], 0],
  ["medium", "What is the liquid part of blood called?", ["Plasma", "Serum", "Lymph", "Platelets"], 0],
  ["medium", "Which nutrient gives the most energy per gram?", ["Fat", "Protein", "Carbohydrate", "Fibre"], 0],
  ["medium", "What do we call organisms that make their own food?", ["Autotrophs", "Heterotrophs", "Saprotrophs", "Parasites"], 0],
  ["medium", "Which hormone lowers blood sugar?", ["Insulin", "Glucagon", "Adrenaline", "Cortisol"], 0],
  ["medium", "What is the scientific name for modern humans?", ["Homo sapiens", "Homo erectus", "Australopithecus", "Homo habilis"], 0],
  ["medium", "Where does most nutrient absorption happen?", ["The small intestine", "The stomach", "The large intestine", "The oesophagus"], 0],
  ["medium", "What is the study of heredity called?", ["Genetics", "Ecology", "Anatomy", "Taxonomy"], 0],
  ["medium", "Which tissue connects muscle to bone?", ["Tendon", "Ligament", "Cartilage", "Fascia"], 0],
  ["medium", "Which molecule do cells use for energy?", ["ATP", "DNA", "RNA", "NADH"], 0],
  ["medium", "What is the largest part of the human brain?", ["The cerebrum", "The cerebellum", "The brainstem", "The thalamus"], 0],
  ["medium", "Which gas do plants release during photosynthesis?", ["Oxygen", "Carbon dioxide", "Nitrogen", "Methane"], 0],
  ["medium", "What is the name for animals with a backbone?", ["Vertebrates", "Invertebrates", "Arthropods", "Molluscs"], 0],
  ["medium", "Which part of the eye controls how much light enters?", ["The iris", "The retina", "The cornea", "The lens"], 0],
  ["medium", "What is the medical term for the voice box?", ["The larynx", "The pharynx", "The trachea", "The epiglottis"], 0],
  ["medium", "Which vitamin deficiency causes scurvy?", ["Vitamin C", "Vitamin D", "Vitamin B12", "Vitamin A"], 0],
  ["medium", "What is the process of water moving through a membrane?", ["Osmosis", "Diffusion", "Active transport", "Endocytosis"], 0],
  ["medium", "Which blood vessels carry blood away from the heart?", ["Arteries", "Veins", "Capillaries", "Venules"], 0],
  ["medium", "How many lungs does a human have?", ["Two", "One", "Three", "Four"], 0],
  ["medium", "What does the pancreas release to aid digestion?", ["Enzymes", "Bile", "Mucus", "Hormones only"], 0],
  ["medium", "Which structure protects the brain?", ["The skull", "The spine", "The ribcage", "The pelvis"], 0],
  ["medium", "What are the building blocks of proteins?", ["Amino acids", "Fatty acids", "Nucleotides", "Monosaccharides"], 0],
  ["medium", "Which insect produces silk?", ["The silkworm", "The honeybee", "The dragonfly", "The cricket"], 0],
  ["hard", "Who proposed evolution by natural selection?", ["Charles Darwin", "Gregor Mendel", "Jean-Baptiste Lamarck", "Carl Linnaeus"], 0],
  ["hard", "Which base replaces thymine in RNA?", ["Uracil", "Cytosine", "Guanine", "Adenine"], 0],
  ["hard", "Which enzyme unwinds DNA during replication?", ["Helicase", "Ligase", "Polymerase", "Primase"], 0],
  ["hard", "What is the physical expression of a gene called?", ["Phenotype", "Genotype", "Allele", "Locus"], 0],
  ["hard", "Which organelle has its own DNA besides the nucleus?", ["The mitochondrion", "The ribosome", "The lysosome", "The vacuole"], 0],
  ["hard", "Which part of a neuron carries signals away from the cell body?", ["The axon", "The dendrite", "The soma", "The synapse"], 0],
  ["hard", "What is the pH range of healthy human blood?", ["7.35 to 7.45", "6.5 to 7.0", "7.8 to 8.2", "5.5 to 6.5"], 0],
  ["hard", "Which stage of respiration produces the most ATP?", ["Oxidative phosphorylation", "Glycolysis", "The Krebs cycle", "Fermentation"], 0],
  ["hard", "Which immunity comes from antibodies passed mother to child?", ["Passive immunity", "Active immunity", "Innate immunity", "Herd immunity"], 0],
  ["hard", "Which taxonomic rank sits directly above genus?", ["Family", "Order", "Species", "Class"], 0],
  ["hard", "What is programmed cell death called?", ["Apoptosis", "Necrosis", "Autolysis", "Lysis"], 0],
  ["hard", "An organism with two different alleles for a trait is called what?", ["Heterozygous", "Homozygous", "Hemizygous", "Polyploid"], 0],
  ["hard", "Who is considered the father of modern genetics?", ["Gregor Mendel", "Charles Darwin", "James Watson", "Thomas Morgan"], 0],
  ["hard", "What is the fluid inside a cell called?", ["Cytoplasm", "Nucleoplasm", "Protoplasm only", "Plasma"], 0],
  ["hard", "Which process converts glucose to pyruvate?", ["Glycolysis", "The Krebs cycle", "Photosynthesis", "Fermentation"], 0],
  ["hard", "What is the term for two species evolving in response to each other?", ["Coevolution", "Convergent evolution", "Divergent evolution", "Adaptive radiation"], 0],
  ["hard", "Which structure in plants controls gas exchange?", ["Stomata", "Xylem", "Phloem", "Cuticle"], 0],
  ["hard", "What is the name for an animal's role in its ecosystem?", ["Its niche", "Its habitat", "Its biome", "Its territory"], 0],
  ["hard", "Which cells produce antibodies?", ["B cells", "T cells", "Macrophages", "Platelets"], 0],
  ["hard", "What is the term for a population's genetic variety?", ["Genetic diversity", "Gene flow", "Genetic drift", "Speciation"], 0],
  ["hard", "Which vessel carries oxygenated blood to the body?", ["The aorta", "The pulmonary artery", "The vena cava", "The pulmonary vein"], 0],
  ["hard", "What is the study of fungi called?", ["Mycology", "Botany", "Entomology", "Herpetology"], 0],
  ["hard", "Which molecule stores genetic information in most organisms?", ["DNA", "RNA", "ATP", "Protein"], 0],
  ["hard", "What is the term for an organism's complete set of genes?", ["Genome", "Proteome", "Karyotype", "Chromatin"], 0],
  ["hard", "Which plant tissue transports water upward?", ["Xylem", "Phloem", "Cambium", "Cortex"], 0],
  ],
  "General Knowledge": [
  ["easy", "What is the largest mammal on Earth?", ["The blue whale", "The elephant", "The giraffe", "The hippo"], 0],
  ["easy", "How many continents are there?", ["Seven", "Five", "Six", "Eight"], 0],
  ["easy", "What is the chemical symbol for water?", ["H2O", "CO2", "O2", "NaCl"], 0],
  ["easy", "How many sides does a triangle have?", ["Three", "Four", "Five", "Six"], 0],
  ["easy", "What is the opposite of 'ancient'?", ["Modern", "Antique", "Historic", "Aged"], 0],
  ["easy", "Which animal is known as man's best friend?", ["The dog", "The cat", "The horse", "The parrot"], 0],
  ["easy", "How many hours are in two days?", ["48", "24", "36", "72"], 0],
  ["easy", "What do you call frozen water?", ["Ice", "Steam", "Fog", "Frost"], 0],
  ["easy", "Which season comes after summer?", ["Autumn", "Winter", "Spring", "Monsoon"], 0],
  ["easy", "How many wheels does a bicycle have?", ["Two", "Three", "Four", "One"], 0],
  ["easy", "What is the currency of Japan?", ["The yen", "The won", "The yuan", "The baht"], 0],
  ["easy", "What is the smallest prime number?", ["2", "1", "3", "0"], 0],
  ["easy", "Which shape has no corners?", ["A circle", "A square", "A triangle", "A pentagon"], 0],
  ["easy", "How many months have 31 days?", ["Seven", "Six", "Five", "Eight"], 0],
  ["medium", "What does the acronym 'laser' stand for?", ["Light Amplification by Stimulated Emission of Radiation", "Light Adjusted Sound Emission Rate", "Linear Amplified Signal Emission", "Light Absorbed by Simple Emission"], 0],
  ["medium", "Which language has the most native speakers?", ["Mandarin Chinese", "English", "Spanish", "Hindi"], 0],
  ["medium", "What is the study of earthquakes called?", ["Seismology", "Geology", "Meteorology", "Volcanology"], 0],
  ["medium", "Which instrument has 88 keys?", ["The piano", "The organ", "The harpsichord", "The accordion"], 0],
  ["medium", "What is a baby kangaroo called?", ["A joey", "A cub", "A kit", "A calf"], 0],
  ["medium", "How many players are on a chess board at the start?", ["32 pieces", "16 pieces", "24 pieces", "20 pieces"], 0],
  ["medium", "What does a philatelist collect?", ["Stamps", "Coins", "Books", "Maps"], 0],
  ["medium", "What is the fear of confined spaces called?", ["Claustrophobia", "Agoraphobia", "Acrophobia", "Arachnophobia"], 0],
  ["medium", "Which blood type can receive from all others?", ["AB positive", "O negative", "A positive", "B negative"], 0],
  ["medium", "What is the world's most widely consumed beverage after water?", ["Tea", "Coffee", "Beer", "Milk"], 0],
  ["hard", "What is the collective term for a group of crows?", ["A murder", "A flock", "A gaggle", "A parliament"], 0],
  ["hard", "What does the Latin phrase 'carpe diem' mean?", ["Seize the day", "Trust in fate", "Live in peace", "Beware the end"], 0],
  ["hard", "What is the study of word origins called?", ["Etymology", "Entomology", "Ethnology", "Epistemology"], 0],
  ["hard", "Which unit measures the loudness of sound?", ["The decibel", "The hertz", "The watt", "The lumen"], 0],
  ["hard", "What is the only letter not in any US state name?", ["Q", "Z", "X", "J"], 0],
  ["hard", "What does 'i.e.' stand for in Latin?", ["Id est", "In exemplum", "Inter alia", "Ipso facto"], 0],
  ["hard", "What is the term for a word spelled the same backwards?", ["A palindrome", "An anagram", "A homonym", "An acronym"], 0],
  ["hard", "How many bits are in a byte?", ["8", "4", "16", "32"], 0],
  ],
  "Sports": [
  ["easy", "How many rings are on the Olympic flag?", ["Five", "Four", "Six", "Three"], 0],
  ["easy", "In football, how long is a standard match?", ["90 minutes", "60 minutes", "80 minutes", "120 minutes"], 0],
  ["easy", "What colour card sends a footballer off?", ["Red", "Yellow", "Black", "Blue"], 0],
  ["easy", "How often are the Summer Olympics held?", ["Every four years", "Every two years", "Every three years", "Every five years"], 0],
  ["easy", "In tennis, what is a zero score called?", ["Love", "Nil", "Duck", "Blank"], 0],
  ["easy", "Which sport is played at Wimbledon?", ["Tennis", "Golf", "Cricket", "Rowing"], 0],
  ["easy", "How many holes are on a full golf course?", ["18", "9", "12", "24"], 0],
  ["easy", "In which sport do you use a bat and a wicket?", ["Cricket", "Baseball", "Hockey", "Lacrosse"], 0],
  ["easy", "What shape is a standard football pitch?", ["Rectangular", "Oval", "Circular", "Square"], 0],
  ["easy", "Which sport features a slam dunk?", ["Basketball", "Volleyball", "Handball", "Netball"], 0],
  ["medium", "How many periods are in an ice hockey game?", ["Three", "Two", "Four", "Five"], 0],
  ["medium", "In boxing, how long is a standard professional round?", ["Three minutes", "Two minutes", "Four minutes", "Five minutes"], 0],
  ["medium", "What is the maximum break in snooker?", ["147", "155", "140", "150"], 0],
  ["medium", "In athletics, how long is a marathon?", ["42.195 km", "40 km", "45 km", "50 km"], 0],
  ["medium", "How many points is a try worth in rugby union?", ["Five", "Three", "Four", "Six"], 0],
  ["medium", "What is the diameter of a basketball hoop?", ["18 inches", "16 inches", "20 inches", "24 inches"], 0],
  ["medium", "In cricket, how many balls are in an over?", ["Six", "Four", "Five", "Eight"], 0],
  ["medium", "Which martial art means 'gentle way'?", ["Judo", "Karate", "Aikido", "Taekwondo"], 0],
  ["medium", "How many lanes does an Olympic swimming pool have?", ["Eight", "Six", "Ten", "Four"], 0],
  ["medium", "In volleyball, how many touches per side are allowed?", ["Three", "Two", "Four", "Five"], 0],
  ["hard", "What is the term for three strikes in a row in bowling?", ["A turkey", "A hat-trick", "A triple", "A trifecta"], 0],
  ["hard", "In fencing, which weapon allows hits with the whole blade?", ["The sabre", "The foil", "The epee", "The rapier"], 0],
  ["hard", "How high is a regulation basketball hoop?", ["10 feet", "9 feet", "12 feet", "8 feet"], 0],
  ["hard", "What is the penalty spot distance in football?", ["12 yards", "10 yards", "15 yards", "18 yards"], 0],
  ["hard", "In golf, what is two under par on a hole called?", ["An eagle", "A birdie", "An albatross", "A bogey"], 0],
  ["hard", "How many players are in a water polo team in the pool?", ["Seven", "Six", "Eight", "Five"], 0],
  ["hard", "What is the weight of a men's shot put?", ["7.26 kg", "5 kg", "10 kg", "4 kg"], 0],
  ["hard", "Which country originated the sport of judo?", ["Japan", "China", "Korea", "Thailand"], 0],
  ],
  "Technology": [
  ["easy", "What does 'www' stand for?", ["World Wide Web", "World Web Works", "Wide World Web", "Web Wide World"], 0],
  ["easy", "Which company makes the iPhone?", ["Apple", "Samsung", "Google", "Microsoft"], 0],
  ["easy", "What device stores files permanently in a computer?", ["The hard drive", "The RAM", "The CPU", "The monitor"], 0],
  ["easy", "What do you call unwanted email?", ["Spam", "Ham", "Junk mail only", "Phish"], 0],
  ["easy", "What does a mouse do on a computer?", ["Moves the cursor", "Stores data", "Prints pages", "Cools the CPU"], 0],
  ["easy", "Which key deletes the character to the left?", ["Backspace", "Delete", "Shift", "Escape"], 0],
  ["easy", "What is the brain of a computer called?", ["The CPU", "The GPU", "The RAM", "The BIOS"], 0],
  ["easy", "What does a firewall protect against?", ["Unauthorised network access", "Overheating", "Power surges", "Dust"], 0],
  ["easy", "What is a common shortcut to copy?", ["Ctrl+C", "Ctrl+V", "Ctrl+X", "Ctrl+Z"], 0],
  ["easy", "Which of these is an operating system?", ["Linux", "Firefox", "Photoshop", "Excel"], 0],
  ["medium", "What does 'open source' mean?", ["The source code is publicly available", "The software is free of charge", "It runs on any device", "It has no licence"], 0],
  ["medium", "What is the binary equivalent of the decimal number 8?", ["1000", "1100", "0111", "1010"], 0],
  ["medium", "Which protocol secures web traffic?", ["HTTPS", "HTTP", "FTP", "SMTP"], 0],
  ["medium", "What does 'cloud computing' mean?", ["Using remote servers over the internet", "Wireless networking", "Weather modelling", "Satellite internet"], 0],
  ["medium", "What is a bug in software?", ["An error in the code", "A virus", "A hardware fault", "A slow connection"], 0],
  ["medium", "What does 'phishing' attempt to steal?", ["Personal information", "Bandwidth", "Storage", "Processing power"], 0],
  ["medium", "Which company developed the Android operating system?", ["Google", "Apple", "Samsung", "Microsoft"], 0],
  ["medium", "What does a compiler do?", ["Turns source code into machine code", "Runs code line by line", "Formats code", "Stores code"], 0],
  ["medium", "What is the smallest unit of digital information?", ["A bit", "A byte", "A nibble", "A word"], 0],
  ["medium", "What does 'bandwidth' measure?", ["Data transfer capacity", "Storage size", "Processor speed", "Screen resolution"], 0],
  ["hard", "What does 'RAID' stand for in storage?", ["Redundant Array of Independent Disks", "Rapid Access Internal Drive", "Random Allocation of Indexed Data", "Remote Array of Integrated Disks"], 0],
  ["hard", "Which port does HTTPS use by default?", ["443", "80", "22", "21"], 0],
  ["hard", "What does 'DDoS' stand for?", ["Distributed Denial of Service", "Direct Denial of Signal", "Dynamic Data over Sockets", "Dual Domain Server"], 0],
  ["hard", "In programming, what is recursion?", ["A function calling itself", "A loop that never ends", "Copying a variable", "Reversing an array"], 0],
  ["hard", "What is Moore's law about?", ["Transistor density doubling over time", "Network value scaling", "Storage cost falling", "Bandwidth growth"], 0],
  ["hard", "What does 'SSH' provide?", ["Secure remote shell access", "Fast file compression", "Encrypted email", "Wireless pairing"], 0],
  ["hard", "What is the default port for SSH?", ["22", "80", "443", "3306"], 0],
  ["hard", "What does 'ACID' describe in databases?", ["Transaction reliability guarantees", "A query language", "An index structure", "A backup format"], 0],
  ],
  "Pop Culture": [
  ["easy", "How many strings does a violin have?", ["Four", "Six", "Five", "Three"], 0],
  ["easy", "Which colour is made by mixing red and white?", ["Pink", "Purple", "Orange", "Grey"], 0],
  ["easy", "How many acts are in a typical Shakespeare play?", ["Five", "Three", "Four", "Two"], 0],
  ["easy", "What is the name of Sherlock Holmes's assistant?", ["Dr Watson", "Dr Jekyll", "Inspector Poirot", "Mr Hyde"], 0],
  ["easy", "Which instrument does a drummer play?", ["Percussion", "Strings", "Brass", "Woodwind"], 0],
  ["easy", "In theatre, what does 'break a leg' mean?", ["Good luck", "Be careful", "Start now", "Leave quickly"], 0],
  ["easy", "What is a haiku?", ["A short Japanese poem", "A folk dance", "A drum rhythm", "A painting style"], 0],
  ["easy", "How many lines does a sonnet have?", ["14", "12", "16", "10"], 0],
  ["medium", "Which art movement is Salvador Dali associated with?", ["Surrealism", "Cubism", "Impressionism", "Baroque"], 0],
  ["medium", "What is the term for a song sung by one person?", ["A solo", "A duet", "A chorus", "An ensemble"], 0],
  ["medium", "Which literary device compares using 'like' or 'as'?", ["A simile", "A metaphor", "Personification", "Alliteration"], 0],
  ["medium", "What is the standard number of players in an orchestra string section?", ["The largest section", "The smallest section", "Exactly ten", "Exactly four"], 0],
  ["medium", "Which dance originated in Argentina?", ["The tango", "The salsa", "The flamenco", "The waltz"], 0],
  ["medium", "What does 'a cappella' mean?", ["Singing without instruments", "Singing very loudly", "A solo performance", "A church hymn"], 0],
  ["medium", "Which art movement did Claude Monet belong to?", ["Impressionism", "Cubism", "Surrealism", "Realism"], 0],
  ["medium", "What is the name for a play's opening act?", ["The exposition", "The climax", "The denouement", "The epilogue"], 0],
  ["hard", "What is the term for the highest female singing voice?", ["Soprano", "Alto", "Contralto", "Mezzo"], 0],
  ["hard", "Which Italian term means 'gradually getting louder'?", ["Crescendo", "Diminuendo", "Staccato", "Legato"], 0],
  ["hard", "Who wrote the play 'A Doll's House'?", ["Henrik Ibsen", "Anton Chekhov", "Oscar Wilde", "George Bernard Shaw"], 0],
  ["hard", "What is a triptych?", ["A three-panelled artwork", "A three-act play", "A three-line poem", "A trio of musicians"], 0],
  ["hard", "Which poetic metre has five feet per line?", ["Pentameter", "Tetrameter", "Hexameter", "Trimeter"], 0],
  ["hard", "What is chiaroscuro in painting?", ["Strong contrast between light and dark", "Blending colours smoothly", "Painting on wet plaster", "Using only primary colours"], 0],
  ],
  "Food & Cooking": [
  ["easy", "What is the main ingredient in guacamole?", ["Avocado", "Tomato", "Cucumber", "Pea"], 0],
  ["easy", "Which fruit is known for being high in potassium?", ["Banana", "Apple", "Grape", "Peach"], 0],
  ["easy", "What is the main ingredient in bread?", ["Flour", "Sugar", "Butter", "Milk"], 0],
  ["easy", "Which vegetable makes you cry when cut?", ["Onion", "Carrot", "Potato", "Cabbage"], 0],
  ["easy", "What is dried grape called?", ["A raisin", "A prune", "A date", "A fig"], 0],
  ["easy", "Which drink is made from roasted beans?", ["Coffee", "Tea", "Cocoa", "Cider"], 0],
  ["easy", "What is the main ingredient in an omelette?", ["Eggs", "Cheese", "Flour", "Milk"], 0],
  ["easy", "Which spice is the most expensive by weight?", ["Saffron", "Cinnamon", "Black pepper", "Nutmeg"], 0],
  ["easy", "What is tofu made from?", ["Soybeans", "Rice", "Wheat", "Corn"], 0],
  ["easy", "Which nut is used to make marzipan?", ["Almond", "Walnut", "Cashew", "Pecan"], 0],
  ["medium", "What does 'al dente' describe?", ["Pasta cooked firm to the bite", "Food served cold", "Meat cooked rare", "Sauce reduced thick"], 0],
  ["medium", "Which acid gives lemons their sour taste?", ["Citric acid", "Acetic acid", "Lactic acid", "Malic acid"], 0],
  ["medium", "What is the process of preserving food in vinegar called?", ["Pickling", "Curing", "Smoking", "Fermenting"], 0],
  ["medium", "Which cheese is traditionally used on pizza?", ["Mozzarella", "Cheddar", "Brie", "Feta"], 0],
  ["medium", "What leavening agent makes bread rise?", ["Yeast", "Baking powder only", "Salt", "Sugar"], 0],
  ["medium", "Which cut of beef is used for a classic steak tartare?", ["Raw beef", "Slow-cooked brisket", "Smoked rib", "Cured flank"], 0],
  ["medium", "What is the base of a hollandaise sauce?", ["Egg yolk and butter", "Flour and milk", "Tomato and onion", "Cream and cheese"], 0],
  ["medium", "Which grain is used to make traditional risotto?", ["Arborio rice", "Basmati rice", "Couscous", "Bulgur"], 0],
  ["hard", "What are the five classic French mother sauces?", ["B\u00e9chamel, velout\u00e9, espagnole, hollandaise and tomato", "B\u00e9chamel, aioli, pesto, roux and gravy", "Velout\u00e9, ranch, tomato, cream and butter", "Espagnole, jus, glaze, stock and demi"], 0],
  ["hard", "What does 'mise en place' mean?", ["Everything prepared and in position", "Cooked to order", "Served at room temperature", "Plated at the pass"], 0],
  ["hard", "Which chemical reaction browns seared meat?", ["The Maillard reaction", "Caramelisation", "Oxidation", "Fermentation"], 0],
  ["hard", "What is umami?", ["The savoury fifth basic taste", "A Japanese noodle", "A cooking technique", "A type of seaweed"], 0],
  ["hard", "At what temperature does water boil at sea level?", ["100 \u00b0C", "90 \u00b0C", "110 \u00b0C", "95 \u00b0C"], 0],
  ["hard", "What is the term for cooking sous vide?", ["Sealed in a bag in a water bath", "Over an open flame", "Under a heat lamp", "In a pressure cooker"], 0],
  ],
  "History": [
  ["easy", "Which empire built the Colosseum?", ["The Roman Empire", "The Greek Empire", "The Ottoman Empire", "The Byzantine Empire"], 0],
  ["easy", "Which country gifted the Statue of Liberty to the USA?", ["France", "Britain", "Spain", "Italy"], 0],
  ["easy", "The Olympic Games originated in which country?", ["Greece", "Italy", "Egypt", "Turkey"], 0],
  ["easy", "Which wall was built to protect ancient China?", ["The Great Wall", "Hadrian's Wall", "The Berlin Wall", "The Western Wall"], 0],
  ["medium", "Which pandemic killed roughly a third of Europe in the 1300s?", ["The Black Death", "The Spanish Flu", "Cholera", "Smallpox"], 0],
  ["medium", "The Industrial Revolution began in which country?", ["Britain", "France", "Germany", "The United States"], 0],
  ["medium", "Which country was the first to give women the national vote?", ["New Zealand", "The United States", "The United Kingdom", "Australia"], 0],
  ["medium", "Apartheid was the official policy of which country?", ["South Africa", "Rhodesia", "Namibia", "Angola"], 0],
  ["medium", "The Rosetta Stone helped decipher which writing system?", ["Egyptian hieroglyphs", "Cuneiform", "Linear B", "Mayan glyphs"], 0],
  ["hard", "The Peloponnesian War was fought between Athens and which city?", ["Sparta", "Thebes", "Corinth", "Argos"], 0],
  ["hard", "The Meiji Restoration modernised which country?", ["Japan", "China", "Korea", "Thailand"], 0],
  ["hard", "The Hundred Years' War was fought between England and whom?", ["France", "Spain", "Scotland", "The Netherlands"], 0],
  ["hard", "Which African kingdom was ruled by Mansa Musa?", ["Mali", "Songhai", "Ghana", "Benin"], 0],
  ["hard", "The Berlin Conference of 1884 divided which continent?", ["Africa", "Asia", "South America", "Oceania"], 0],
  ],
};
