/**
 * Shortfall-closing rows.
 *
 * Sized against the gaps the build reported after data3: mostly easy and
 * medium, since the derived generators skew hard (obscure countries, rare
 * elements, specialist terms).
 */
type F = { q: string; a: string; pool: string[]; d: 'easy' | 'medium' | 'hard' };

export const GEO_FACTS: F[] = [
  { q: 'Which is the largest continent by area?', a: 'Asia', pool: ['Africa', 'North America', 'Europe'], d: 'easy' },
  { q: 'Which continent is the coldest?', a: 'Antarctica', pool: ['Europe', 'Asia', 'South America'], d: 'easy' },
  { q: 'How many continents are there?', a: 'Seven', pool: ['Five', 'Six', 'Eight'], d: 'easy' },
  { q: 'Which line divides Earth into northern and southern halves?', a: 'The Equator', pool: ['The Prime Meridian', 'The Tropic of Cancer', 'The Arctic Circle'], d: 'easy' },
  { q: 'What is a large area of land surrounded by water called?', a: 'An island', pool: ['A peninsula', 'An isthmus', 'A delta'], d: 'easy' },
  { q: 'Roughly what fraction of Earth’s surface is water?', a: 'About 70%', pool: ['About 30%', 'About 50%', 'About 90%'], d: 'easy' },
  { q: 'What is molten rock below the surface called?', a: 'Magma', pool: ['Lava', 'Basalt', 'Granite'], d: 'easy' },
  { q: 'Which direction does the Sun rise from?', a: 'The east', pool: ['The west', 'The north', 'The south'], d: 'easy' },
  { q: 'What do we call a period of unusually low rainfall?', a: 'A drought', pool: ['A monsoon', 'A cyclone', 'A blizzard'], d: 'easy' },
  { q: 'What is the imaginary line at 0° longitude called?', a: 'The Prime Meridian', pool: ['The Equator', 'The International Date Line', 'The Tropic of Capricorn'], d: 'easy' },
  { q: 'Which instrument shows direction using magnetism?', a: 'A compass', pool: ['A sextant', 'A barometer', 'An altimeter'], d: 'easy' },
  { q: 'What is a very dry region with little rainfall called?', a: 'A desert', pool: ['A tundra', 'A savanna', 'A steppe'], d: 'easy' },
  { q: 'What do contour lines on a map show?', a: 'Elevation', pool: ['Temperature', 'Population', 'Rainfall'], d: 'easy' },
  { q: 'Which type of map shows political borders?', a: 'A political map', pool: ['A topographic map', 'A climate map', 'A road map'], d: 'easy' },
  { q: 'What is frozen water at the poles mainly called?', a: 'Ice', pool: ['Permafrost only', 'Sleet', 'Hail'], d: 'easy' },
  { q: 'What is the flat land at a river’s mouth called?', a: 'A delta', pool: ['A canyon', 'A plateau', 'A fjord'], d: 'easy' },
  { q: 'Which season is opposite in the southern hemisphere?', a: 'All of them', pool: ['Only summer', 'Only winter', 'None of them'], d: 'easy' },
  { q: 'What is a chain of mountains called?', a: 'A range', pool: ['A ridge', 'A basin', 'A valley'], d: 'easy' },
  { q: 'Which body of water is salty?', a: 'The ocean', pool: ['A river', 'A pond', 'A stream'], d: 'easy' },
  { q: 'What causes tides on Earth?', a: 'The Moon’s gravity', pool: ['Wind', 'Earth’s rotation alone', 'Ocean currents'], d: 'easy' },
  { q: 'What is the study of maps called?', a: 'Cartography', pool: ['Geology', 'Meteorology', 'Topography'], d: 'medium' },
  { q: 'What is a narrow strip of land joining two larger areas?', a: 'An isthmus', pool: ['A peninsula', 'A strait', 'A cape'], d: 'medium' },
  { q: 'What is a narrow channel of water joining two seas?', a: 'A strait', pool: ['An isthmus', 'A bay', 'A gulf'], d: 'medium' },
  { q: 'Which climate zone lies between the tropics?', a: 'Tropical', pool: ['Temperate', 'Polar', 'Arid'], d: 'medium' },
  { q: 'What is the movement of Earth’s plates called?', a: 'Plate tectonics', pool: ['Erosion', 'Weathering', 'Sedimentation'], d: 'medium' },
  { q: 'What is a deep valley carved by a glacier and flooded by sea?', a: 'A fjord', pool: ['A canyon', 'A gorge', 'A ravine'], d: 'medium' },
  { q: 'What kind of rock forms from cooled magma?', a: 'Igneous', pool: ['Sedimentary', 'Metamorphic', 'Organic'], d: 'medium' },
  { q: 'What is the outermost layer of Earth called?', a: 'The crust', pool: ['The mantle', 'The outer core', 'The inner core'], d: 'medium' },
  { q: 'What is a landlocked country?', a: 'One with no sea coast', pool: ['One with no rivers', 'One entirely desert', 'One made of islands'], d: 'medium' },
  { q: 'What is the wearing away of rock by wind and water called?', a: 'Erosion', pool: ['Deposition', 'Subduction', 'Condensation'], d: 'medium' },
];

export const CHEM_FACTS: F[] = [
  { q: 'What is the chemical formula for water?', a: 'H₂O', pool: ['CO₂', 'O₂', 'H₂O₂'], d: 'easy' },
  { q: 'What is table salt chemically?', a: 'Sodium chloride', pool: ['Potassium chloride', 'Calcium carbonate', 'Sodium bicarbonate'], d: 'easy' },
  { q: 'Which gas do plants absorb from the air?', a: 'Carbon dioxide', pool: ['Oxygen', 'Nitrogen', 'Hydrogen'], d: 'easy' },
  { q: 'What is the lightest element?', a: 'Hydrogen', pool: ['Helium', 'Lithium', 'Carbon'], d: 'easy' },
  { q: 'What are the three common states of matter?', a: 'Solid, liquid, gas', pool: ['Solid, liquid, plasma', 'Hot, cold, warm', 'Metal, gas, crystal'], d: 'easy' },
  { q: 'What is the smallest unit of an element?', a: 'An atom', pool: ['A molecule', 'A cell', 'A compound'], d: 'easy' },
  { q: 'Which metal is liquid at room temperature?', a: 'Mercury', pool: ['Lead', 'Tin', 'Zinc'], d: 'easy' },
  { q: 'What does an acid taste like?', a: 'Sour', pool: ['Sweet', 'Bitter', 'Salty'], d: 'easy' },
  { q: 'What is rust made of?', a: 'Iron oxide', pool: ['Copper oxide', 'Iron sulphide', 'Iron chloride'], d: 'easy' },
  { q: 'What do we call a substance made of two or more elements bonded?', a: 'A compound', pool: ['A mixture', 'An isotope', 'An alloy'], d: 'easy' },
  { q: 'What gas makes up most of Earth’s atmosphere?', a: 'Nitrogen', pool: ['Oxygen', 'Carbon dioxide', 'Argon'], d: 'easy' },
  { q: 'What is the process of a liquid becoming a gas?', a: 'Evaporation', pool: ['Condensation', 'Freezing', 'Melting'], d: 'easy' },
  { q: 'What is the chemical symbol for gold?', a: 'Au', pool: ['Ag', 'Go', 'Gd'], d: 'easy' },
  { q: 'Which gas do we breathe out most of alongside nitrogen?', a: 'Carbon dioxide', pool: ['Hydrogen', 'Helium', 'Methane'], d: 'easy' },
  { q: 'At what temperature does water freeze in Celsius?', a: '0 °C', pool: ['100 °C', '32 °C', '-10 °C'], d: 'easy' },
  { q: 'At what temperature does water boil at sea level?', a: '100 °C', pool: ['0 °C', '212 °C', '90 °C'], d: 'easy' },
  { q: 'What is a mixture of metals called?', a: 'An alloy', pool: ['A compound', 'A solution', 'A suspension'], d: 'easy' },
  { q: 'What kind of substance turns litmus paper red?', a: 'An acid', pool: ['A base', 'A salt', 'A neutral substance'], d: 'easy' },
  { q: 'Which element do all organic compounds contain?', a: 'Carbon', pool: ['Nitrogen', 'Sulphur', 'Phosphorus'], d: 'easy' },
  { q: 'What is dry ice?', a: 'Solid carbon dioxide', pool: ['Very cold water ice', 'Solid nitrogen', 'Frozen alcohol'], d: 'easy' },
  { q: 'What is the pH of a neutral solution?', a: '7', pool: ['0', '14', '1'], d: 'easy' },
  { q: 'What does a catalyst do?', a: 'Speeds a reaction without being used up', pool: ['Slows a reaction', 'Is consumed by the reaction', 'Changes the products'], d: 'medium' },
  { q: 'What is an isotope?', a: 'An atom with a different number of neutrons', pool: ['An atom with extra electrons', 'A charged atom', 'A molecule of one element'], d: 'medium' },
  { q: 'What holds atoms together in a molecule?', a: 'Chemical bonds', pool: ['Gravity', 'Friction', 'Magnetism'], d: 'medium' },
  { q: 'What is an ion?', a: 'An atom with a net electric charge', pool: ['An atom with extra neutrons', 'A neutral molecule', 'A radioactive atom'], d: 'medium' },
  { q: 'What type of bond involves sharing electrons?', a: 'Covalent', pool: ['Ionic', 'Metallic', 'Hydrogen'], d: 'medium' },
  { q: 'What type of bond involves transferring electrons?', a: 'Ionic', pool: ['Covalent', 'Metallic', 'Van der Waals'], d: 'medium' },
  { q: 'What does the periodic table organise elements by?', a: 'Atomic number', pool: ['Atomic mass only', 'Discovery date', 'Alphabetical order'], d: 'medium' },
  { q: 'What is a solution’s solvent?', a: 'The substance doing the dissolving', pool: ['The substance dissolved', 'The container', 'The residue'], d: 'medium' },
  { q: 'What reaction releases heat?', a: 'An exothermic reaction', pool: ['An endothermic reaction', 'A reversible reaction', 'A neutral reaction'], d: 'medium' },
  { q: 'What is oxidation?', a: 'Loss of electrons', pool: ['Gain of electrons', 'Loss of protons', 'Gain of neutrons'], d: 'medium' },
  { q: 'What does a base do to an acid?', a: 'Neutralises it', pool: ['Strengthens it', 'Evaporates it', 'Freezes it'], d: 'medium' },
  { q: 'Which group of elements is least reactive?', a: 'The noble gases', pool: ['The alkali metals', 'The halogens', 'The transition metals'], d: 'medium' },
  { q: 'Which group of metals reacts violently with water?', a: 'The alkali metals', pool: ['The noble gases', 'The transition metals', 'The lanthanides'], d: 'medium' },
  { q: 'What is a mole in chemistry?', a: 'A fixed number of particles', pool: ['A unit of mass', 'A unit of volume', 'A type of bond'], d: 'medium' },
  { q: 'What is distillation used to do?', a: 'Separate liquids by boiling point', pool: ['Separate solids by size', 'Remove colour', 'Increase concentration only'], d: 'medium' },
  { q: 'What is a polymer?', a: 'A long chain of repeating units', pool: ['A single small molecule', 'A metal alloy', 'A type of acid'], d: 'medium' },
];

export const PHYS_FACTS2: F[] = [
  { q: 'What unit is force measured in?', a: 'Newtons', pool: ['Joules', 'Watts', 'Pascals'], d: 'easy' },
  { q: 'What unit is energy measured in?', a: 'Joules', pool: ['Newtons', 'Amperes', 'Volts'], d: 'easy' },
  { q: 'What unit is power measured in?', a: 'Watts', pool: ['Joules', 'Newtons', 'Ohms'], d: 'easy' },
  { q: 'What unit is electric current measured in?', a: 'Amperes', pool: ['Volts', 'Ohms', 'Watts'], d: 'easy' },
  { q: 'What does a battery provide to a circuit?', a: 'Voltage', pool: ['Resistance', 'Frequency', 'Mass'], d: 'easy' },
  { q: 'What happens when you rub two surfaces together?', a: 'Heat is produced', pool: ['They cool down', 'They become magnetic', 'They gain mass'], d: 'easy' },
  { q: 'Which is heavier, a kilogram of iron or a kilogram of feathers?', a: 'They weigh the same', pool: ['The iron', 'The feathers', 'It depends on volume'], d: 'easy' },
  { q: 'What does a prism do to white light?', a: 'Splits it into colours', pool: ['Absorbs it', 'Makes it brighter', 'Bends it without change'], d: 'easy' },
  { q: 'Why does a ball stop rolling on grass?', a: 'Friction slows it', pool: ['Gravity stops it', 'It runs out of mass', 'Air adds weight'], d: 'easy' },
  { q: 'What do we call the pull of Earth on an object?', a: 'Weight', pool: ['Mass', 'Density', 'Volume'], d: 'easy' },
  { q: 'Which floats: an object less dense than water, or more dense?', a: 'Less dense', pool: ['More dense', 'Equally dense only', 'Neither floats'], d: 'easy' },
  { q: 'What kind of energy does food store?', a: 'Chemical energy', pool: ['Kinetic energy', 'Nuclear energy', 'Sound energy'], d: 'easy' },
  { q: 'What do solar panels convert sunlight into?', a: 'Electrical energy', pool: ['Sound energy', 'Nuclear energy', 'Chemical energy'], d: 'easy' },
  { q: 'What blocks light completely to form a shadow?', a: 'An opaque object', pool: ['A transparent object', 'A translucent object', 'A reflective object'], d: 'easy' },
  { q: 'What is an echo?', a: 'Reflected sound', pool: ['Refracted sound', 'Absorbed sound', 'Amplified sound'], d: 'easy' },
  { q: 'Which material conducts electricity best?', a: 'Copper', pool: ['Rubber', 'Glass', 'Wood'], d: 'easy' },
  { q: 'What is an insulator?', a: 'A material that resists current flow', pool: ['A material that conducts well', 'A magnetic material', 'A radioactive material'], d: 'easy' },
  { q: 'What shape is the path of a thrown ball?', a: 'A curve', pool: ['A straight line', 'A circle', 'A spiral'], d: 'easy' },
  { q: 'What happens to your weight on the Moon?', a: 'It decreases', pool: ['It increases', 'It stays the same', 'It becomes zero'], d: 'easy' },
  { q: 'What causes day and night?', a: 'Earth’s rotation', pool: ['Earth’s orbit', 'The Moon’s orbit', 'The Sun’s rotation'], d: 'easy' },
  { q: 'What causes the seasons?', a: 'Earth’s tilted axis', pool: ['Distance from the Sun', 'The Moon’s phases', 'Solar flares'], d: 'medium' },
  { q: 'What unit is resistance measured in?', a: 'Ohms', pool: ['Volts', 'Amperes', 'Farads'], d: 'medium' },
  { q: 'What unit is frequency measured in?', a: 'Hertz', pool: ['Decibels', 'Watts', 'Newtons'], d: 'medium' },
  { q: 'What unit is pressure measured in?', a: 'Pascals', pool: ['Newtons', 'Joules', 'Kelvin'], d: 'medium' },
  { q: 'What is density?', a: 'Mass per unit volume', pool: ['Weight per unit area', 'Force per unit time', 'Volume per unit mass'], d: 'medium' },
  { q: 'What is work in physics?', a: 'Force times distance moved', pool: ['Mass times velocity', 'Power times resistance', 'Energy divided by time'], d: 'medium' },
  { q: 'What is power in physics?', a: 'Energy transferred per second', pool: ['Force times mass', 'Work times time', 'Voltage times resistance'], d: 'medium' },
  { q: 'What does Ohm’s law relate?', a: 'Voltage, current and resistance', pool: ['Force, mass and acceleration', 'Pressure, volume and temperature', 'Energy, mass and light speed'], d: 'medium' },
  { q: 'In a series circuit, what is the same everywhere?', a: 'The current', pool: ['The voltage', 'The resistance', 'The power'], d: 'medium' },
  { q: 'In a parallel circuit, what is the same across each branch?', a: 'The voltage', pool: ['The current', 'The resistance', 'The charge'], d: 'medium' },
  { q: 'What happens to the pitch of a sound if frequency rises?', a: 'It gets higher', pool: ['It gets lower', 'It stays the same', 'It gets quieter'], d: 'medium' },
  { q: 'What determines the loudness of a sound?', a: 'Its amplitude', pool: ['Its frequency', 'Its wavelength', 'Its speed'], d: 'medium' },
  { q: 'What is terminal velocity?', a: 'The constant speed when drag balances weight', pool: ['The fastest possible speed', 'Speed at the end of a fall', 'The speed of sound'], d: 'medium' },
  { q: 'What is a lever’s pivot point called?', a: 'The fulcrum', pool: ['The load', 'The effort', 'The axle'], d: 'medium' },
  { q: 'Which travels through a vacuum: sound or light?', a: 'Light', pool: ['Sound', 'Both', 'Neither'], d: 'medium' },
  { q: 'What is Newton’s third law?', a: 'Every action has an equal and opposite reaction', pool: ['Force equals mass times acceleration', 'Objects stay at rest unless acted on', 'Energy cannot be created'], d: 'hard' },
  { q: 'What is Newton’s second law?', a: 'Force equals mass times acceleration', pool: ['Action equals reaction', 'Objects resist changes in motion', 'Energy is conserved'], d: 'hard' },
  { q: 'What is Newton’s first law also called?', a: 'The law of inertia', pool: ['The law of momentum', 'The law of gravitation', 'The law of energy'], d: 'hard' },
  { q: 'What does Boyle’s law relate at constant temperature?', a: 'Pressure and volume', pool: ['Pressure and temperature', 'Volume and temperature', 'Mass and volume'], d: 'hard' },
  { q: 'What is the first law of thermodynamics?', a: 'Energy is conserved', pool: ['Entropy always increases', 'Heat flows from hot to cold', 'Absolute zero is unreachable'], d: 'hard' },
  { q: 'What is the unit of capacitance?', a: 'The farad', pool: ['The henry', 'The tesla', 'The weber'], d: 'hard' },
  { q: 'What is the unit of magnetic flux density?', a: 'The tesla', pool: ['The farad', 'The henry', 'The gauss only'], d: 'hard' },
  { q: 'What is the photoelectric work function?', a: 'The minimum energy to eject an electron', pool: ['The energy of a photon', 'The energy of an orbit', 'The binding energy of a nucleus'], d: 'hard' },
  { q: 'What is red shift evidence of?', a: 'An expanding universe', pool: ['A contracting universe', 'A static universe', 'Solar flares'], d: 'hard' },
  { q: 'Which quantity does a Newton-metre measure?', a: 'Torque or work', pool: ['Power', 'Pressure', 'Frequency'], d: 'hard' },
  { q: 'What is nuclear fusion?', a: 'Light nuclei joining to form heavier ones', pool: ['Heavy nuclei splitting apart', 'Electrons leaving atoms', 'Protons decaying'], d: 'hard' },
  { q: 'What is nuclear fission?', a: 'A heavy nucleus splitting apart', pool: ['Light nuclei joining', 'Electron capture', 'Photon emission'], d: 'hard' },
  { q: 'What is the Coriolis effect caused by?', a: 'Earth’s rotation', pool: ['Earth’s magnetic field', 'The Moon’s gravity', 'Ocean salinity'], d: 'hard' },
];
