/** Shortfall-closing rows, part two: the humanities-side categories. */
type F = { q: string; a: string; pool: string[]; d: 'easy' | 'medium' | 'hard' };

export const HIST_FACTS2: F[] = [
  { q: 'What were the ancient Egyptians’ triangular tombs called?', a: 'Pyramids', pool: ['Ziggurats', 'Obelisks', 'Temples'], d: 'easy' },
  { q: 'What material gave the Stone Age its name?', a: 'Stone', pool: ['Bronze', 'Iron', 'Clay'], d: 'easy' },
  { q: 'Which age followed the Bronze Age?', a: 'The Iron Age', pool: ['The Stone Age', 'The Golden Age', 'The Steel Age'], d: 'easy' },
  { q: 'Who were the warriors of medieval Europe on horseback?', a: 'Knights', pool: ['Samurai', 'Legionaries', 'Hoplites'], d: 'easy' },
  { q: 'What is a large fortified building of the Middle Ages?', a: 'A castle', pool: ['A cathedral', 'A monastery', 'A villa'], d: 'easy' },
  { q: 'Which sea did the Vikings mainly sail?', a: 'The North Sea', pool: ['The Red Sea', 'The Black Sea', 'The Caspian Sea'], d: 'easy' },
  { q: 'What did ancient Romans call their arena for gladiators?', a: 'The Colosseum', pool: ['The Pantheon', 'The Forum', 'The Circus'], d: 'easy' },
  { q: 'Which writing system did ancient Egyptians use?', a: 'Hieroglyphs', pool: ['Cuneiform', 'Runes', 'Sanskrit'], d: 'easy' },
  { q: 'What powered the machines of the Industrial Revolution first?', a: 'Steam', pool: ['Electricity', 'Petrol', 'Nuclear power'], d: 'easy' },
  { q: 'Which century was the year 1850 in?', a: 'The 19th', pool: ['The 18th', 'The 20th', 'The 17th'], d: 'easy' },
  { q: 'What does BC stand for in dates?', a: 'Before Christ', pool: ['Before Century', 'British Calendar', 'Before Counting'], d: 'easy' },
  { q: 'Which ancient people are credited with early democracy?', a: 'The Athenians', pool: ['The Spartans', 'The Romans', 'The Persians'], d: 'easy' },
  { q: 'What was the currency of the Roman Empire?', a: 'The denarius', pool: ['The drachma', 'The shekel', 'The florin'], d: 'medium' },
  { q: 'What is a person who studies the past through objects called?', a: 'An archaeologist', pool: ['A historian', 'A geologist', 'An anthropologist'], d: 'easy' },
  { q: 'Which ocean did Columbus cross in 1492?', a: 'The Atlantic', pool: ['The Pacific', 'The Indian', 'The Arctic'], d: 'easy' },
  { q: 'Which war was fought from 1914 to 1918?', a: 'World War I', pool: ['World War II', 'The Crimean War', 'The Boer War'], d: 'easy' },
  { q: 'Which war was fought from 1939 to 1945?', a: 'World War II', pool: ['World War I', 'The Korean War', 'The Vietnam War'], d: 'easy' },
  { q: 'What was the Berlin Wall built to do?', a: 'Divide East and West Berlin', pool: ['Defend against invasion', 'Mark a national border', 'Contain a flood'], d: 'easy' },
  { q: 'Which country did Mahatma Gandhi help gain independence?', a: 'India', pool: ['Pakistan', 'Sri Lanka', 'Bangladesh'], d: 'easy' },
  { q: 'Who was the American civil rights leader who gave the "I Have a Dream" speech?', a: 'Martin Luther King Jr.', pool: ['Malcolm X', 'Rosa Parks', 'Frederick Douglass'], d: 'easy' },
  { q: 'Which South African leader was imprisoned for 27 years?', a: 'Nelson Mandela', pool: ['Desmond Tutu', 'Steve Biko', 'Thabo Mbeki'], d: 'easy' },
  { q: 'What was the system of racial segregation in South Africa called?', a: 'Apartheid', pool: ['Segregation Act', 'The Colour Bar', 'Jim Crow'], d: 'medium' },
  { q: 'Which US president was assassinated in 1963?', a: 'John F. Kennedy', pool: ['Abraham Lincoln', 'Franklin Roosevelt', 'Woodrow Wilson'], d: 'medium' },
  { q: 'Which US president abolished slavery?', a: 'Abraham Lincoln', pool: ['George Washington', 'Andrew Jackson', 'Ulysses Grant'], d: 'medium' },
  { q: 'Which country did the USA declare independence from?', a: 'Great Britain', pool: ['France', 'Spain', 'The Netherlands'], d: 'easy' },
  { q: 'In what year did the USA declare independence?', a: '1776', pool: ['1786', '1766', '1801'], d: 'medium' },
  { q: 'Which revolution began in France in 1789?', a: 'The French Revolution', pool: ['The Industrial Revolution', 'The July Revolution', 'The Paris Commune'], d: 'medium' },
  { q: 'Who was defeated at the Battle of Waterloo?', a: 'Napoleon', pool: ['Wellington', 'Nelson', 'Blücher'], d: 'medium' },
  { q: 'Which plague killed much of Europe in the 14th century?', a: 'The Black Death', pool: ['The Spanish Flu', 'Cholera', 'Smallpox'], d: 'medium' },
  { q: 'What was the Reformation about?', a: 'Splitting from the Catholic Church', pool: ['Restoring the Roman Empire', 'Ending feudalism', 'Founding universities'], d: 'medium' },
  { q: 'Who nailed the Ninety-five Theses to a church door?', a: 'Martin Luther', pool: ['John Calvin', 'Henry VIII', 'Thomas More'], d: 'medium' },
  { q: 'Which English king had six wives?', a: 'Henry VIII', pool: ['Henry VII', 'Charles I', 'Edward VI'], d: 'medium' },
  { q: 'Which queen reigned over Britain for most of the 19th century?', a: 'Victoria', pool: ['Elizabeth I', 'Anne', 'Mary I'], d: 'medium' },
  { q: 'What ended the Second World War in the Pacific?', a: 'The atomic bombings and Japan’s surrender', pool: ['The fall of Berlin', 'The Normandy landings', 'The Battle of Britain'], d: 'medium' },
  { q: 'What was D-Day?', a: 'The Allied landings in Normandy', pool: ['The bombing of Dresden', 'The invasion of Poland', 'The liberation of Paris'], d: 'medium' },
  { q: 'Which alliance was formed in 1949 for Western defence?', a: 'NATO', pool: ['The Warsaw Pact', 'The United Nations', 'The European Union'], d: 'medium' },
  { q: 'What was the Space Race between?', a: 'The USA and the USSR', pool: ['The USA and China', 'Britain and France', 'The USSR and China'], d: 'medium' },
  { q: 'Which country launched the first artificial satellite?', a: 'The Soviet Union', pool: ['The USA', 'China', 'Britain'], d: 'medium' },
  { q: 'What was that first satellite called?', a: 'Sputnik', pool: ['Vostok', 'Explorer', 'Apollo'], d: 'medium' },
  { q: 'Which organisation was founded in 1945 to keep world peace?', a: 'The United Nations', pool: ['The League of Nations', 'NATO', 'The Red Cross'], d: 'medium' },
  { q: 'What preceded the United Nations?', a: 'The League of Nations', pool: ['The Warsaw Pact', 'The Commonwealth', 'The Hanseatic League'], d: 'medium' },
  { q: 'Which wall fell in 1989?', a: 'The Berlin Wall', pool: ['Hadrian’s Wall', 'The Great Wall', 'The Western Wall'], d: 'easy' },
  { q: 'Which empire did Britain build across the globe?', a: 'The British Empire', pool: ['The Roman Empire', 'The Dutch Empire', 'The Portuguese Empire'], d: 'easy' },
  { q: 'Which trade route network connected Rome to China?', a: 'The Silk Road', pool: ['The Spice Route', 'The Amber Road', 'The Incense Route'], d: 'medium' },
  { q: 'What was feudalism?', a: 'A system of land held in exchange for service', pool: ['A trading system', 'A religious order', 'A form of democracy'], d: 'medium' },
  { q: 'Who founded the Mongol Empire?', a: 'Genghis Khan', pool: ['Kublai Khan', 'Tamerlane', 'Attila'], d: 'medium' },
  { q: 'Which ancient library was famously destroyed?', a: 'The Library of Alexandria', pool: ['The Library of Pergamum', 'The Vatican Library', 'The Bodleian'], d: 'medium' },
  { q: 'Which ancient city was buried by Vesuvius?', a: 'Pompeii', pool: ['Ostia', 'Carthage', 'Ephesus'], d: 'easy' },
  { q: 'What did the Rosetta Stone help decipher?', a: 'Egyptian hieroglyphs', pool: ['Cuneiform', 'Linear B', 'Mayan glyphs'], d: 'medium' },
  { q: 'Which explorer reached the South Pole first?', a: 'Roald Amundsen', pool: ['Robert Scott', 'Ernest Shackleton', 'Edmund Hillary'], d: 'medium' },
];

export const SPORT_FACTS2: F[] = [
  { q: 'How many players are on a football (soccer) team on the pitch?', a: 'Eleven', pool: ['Ten', 'Twelve', 'Nine'], d: 'easy' },
  { q: 'How many players are on a basketball team on court?', a: 'Five', pool: ['Six', 'Four', 'Seven'], d: 'easy' },
  { q: 'What colour card sends a footballer off?', a: 'Red', pool: ['Yellow', 'Blue', 'Black'], d: 'easy' },
  { q: 'What is the object hit in tennis?', a: 'A ball', pool: ['A shuttlecock', 'A puck', 'A birdie'], d: 'easy' },
  { q: 'How often are the Summer Olympics held?', a: 'Every four years', pool: ['Every two years', 'Every three years', 'Every five years'], d: 'easy' },
  { q: 'What colour is the highest Olympic medal?', a: 'Gold', pool: ['Silver', 'Bronze', 'Platinum'], d: 'easy' },
  { q: 'How many rings are on the Olympic flag?', a: 'Five', pool: ['Four', 'Six', 'Seven'], d: 'easy' },
  { q: 'What sport is played at Wimbledon?', a: 'Tennis', pool: ['Cricket', 'Golf', 'Rugby'], d: 'easy' },
  { q: 'Which sport uses a bat, ball and wickets?', a: 'Cricket', pool: ['Baseball', 'Hockey', 'Rounders'], d: 'easy' },
  { q: 'Which sport uses clubs and a small white ball?', a: 'Golf', pool: ['Hockey', 'Polo', 'Croquet'], d: 'easy' },
  { q: 'Which sport uses a puck on ice?', a: 'Ice hockey', pool: ['Curling', 'Figure skating', 'Bandy'], d: 'easy' },
  { q: 'How long is a standard marathon, roughly?', a: 'About 42 km', pool: ['About 21 km', 'About 30 km', 'About 50 km'], d: 'easy' },
  { q: 'What is the fastest swimming stroke?', a: 'Freestyle', pool: ['Breaststroke', 'Backstroke', 'Butterfly'], d: 'easy' },
  { q: 'In football, who is allowed to use their hands?', a: 'The goalkeeper', pool: ['The striker', 'The captain', 'The defender'], d: 'easy' },
  { q: 'How many holes are on a full golf course?', a: 'Eighteen', pool: ['Nine', 'Twelve', 'Twenty-four'], d: 'easy' },
  { q: 'What is the centre of a dartboard called?', a: 'The bullseye', pool: ['The treble', 'The double', 'The oche'], d: 'easy' },
  { q: 'Which sport takes place in a ring with gloves?', a: 'Boxing', pool: ['Wrestling', 'Judo', 'Fencing'], d: 'easy' },
  { q: 'Which sport uses a horse and a mallet?', a: 'Polo', pool: ['Croquet', 'Cricket', 'Lacrosse'], d: 'easy' },
  { q: 'What is the winning score called in tennis when a set is won?', a: 'A set', pool: ['A frame', 'An inning', 'A round'], d: 'easy' },
  { q: 'How many periods are in an ice hockey game?', a: 'Three', pool: ['Two', 'Four', 'Five'], d: 'medium' },
  { q: 'How many quarters are in an NBA basketball game?', a: 'Four', pool: ['Two', 'Three', 'Five'], d: 'medium' },
  { q: 'How long is a football match, excluding stoppages?', a: '90 minutes', pool: ['60 minutes', '80 minutes', '100 minutes'], d: 'easy' },
  { q: 'How many players are in a rugby union team?', a: 'Fifteen', pool: ['Thirteen', 'Eleven', 'Seventeen'], d: 'medium' },
  { q: 'How many players are in a rugby league team?', a: 'Thirteen', pool: ['Fifteen', 'Eleven', 'Twelve'], d: 'medium' },
  { q: 'How many players are in a volleyball team on court?', a: 'Six', pool: ['Five', 'Seven', 'Four'], d: 'medium' },
  { q: 'How many players are on a baseball team in the field?', a: 'Nine', pool: ['Eight', 'Ten', 'Eleven'], d: 'medium' },
  { q: 'What is a "love" score in tennis?', a: 'Zero', pool: ['Fifteen', 'Forty', 'Deuce'], d: 'medium' },
  { q: 'What does "deuce" mean in tennis?', a: 'The score is tied at 40-40', pool: ['A double fault', 'A tie-break', 'Match point'], d: 'medium' },
  { q: 'What is the highest break in snooker?', a: '147', pool: ['100', '155', '180'], d: 'medium' },
  { q: 'What is the maximum score with three darts?', a: '180', pool: ['150', '170', '200'], d: 'medium' },
  { q: 'What is offside in football broadly about?', a: 'Being ahead of the last defender when the ball is played', pool: ['Stepping off the pitch', 'Fouling from behind', 'Handling the ball'], d: 'medium' },
  { q: 'What is a "birdie" in golf?', a: 'One stroke under par', pool: ['One stroke over par', 'Two under par', 'Level par'], d: 'medium' },
  { q: 'What is a "bogey" in golf?', a: 'One stroke over par', pool: ['One under par', 'Two under par', 'Level par'], d: 'medium' },
  { q: 'What is an "eagle" in golf?', a: 'Two strokes under par', pool: ['One under par', 'Two over par', 'Three under par'], d: 'medium' },
  { q: 'What is a "six" in cricket?', a: 'The ball clearing the boundary without bouncing', pool: ['Six deliveries in an over', 'A six-run penalty', 'Six wickets in an innings'], d: 'medium' },
  { q: 'How many deliveries are in a standard cricket over?', a: 'Six', pool: ['Four', 'Eight', 'Ten'], d: 'medium' },
  { q: 'What is the Ashes contested between?', a: 'England and Australia', pool: ['India and Pakistan', 'England and India', 'Australia and New Zealand'], d: 'medium' },
  { q: 'How often is the FIFA World Cup held?', a: 'Every four years', pool: ['Every two years', 'Every three years', 'Every year'], d: 'easy' },
  { q: 'What is a "Grand Slam" in tennis?', a: 'Winning all four major tournaments', pool: ['Winning a set to love', 'Winning three majors', 'An unbeaten season'], d: 'hard' },
  { q: 'Which four tournaments make up tennis’s Grand Slam?', a: 'Australian Open, French Open, Wimbledon, US Open', pool: ['Wimbledon, US Open, Masters, Davis Cup', 'French Open, Wimbledon, Olympics, US Open', 'Australian Open, Wimbledon, Davis Cup, US Open'], d: 'hard' },
  { q: 'What is the Davis Cup contested in?', a: 'Tennis', pool: ['Golf', 'Sailing', 'Cycling'], d: 'hard' },
  { q: 'In Formula 1, what does a chequered flag signal?', a: 'The end of the race', pool: ['A safety car', 'A penalty', 'A restart'], d: 'medium' },
  { q: 'In Formula 1, what does a yellow flag mean?', a: 'Danger, slow down', pool: ['Race over', 'Overtake allowed', 'Pit now'], d: 'hard' },
  { q: 'What is a pit stop for in motor racing?', a: 'Tyres, fuel and repairs', pool: ['Driver rest only', 'Weighing the car', 'Timing checks'], d: 'medium' },
  { q: 'What is the term for a perfect score in gymnastics historically?', a: 'A ten', pool: ['A nine', 'A hundred', 'A gold'], d: 'hard' },
  { q: 'What is a "peloton" in cycling?', a: 'The main group of riders', pool: ['A lone breakaway', 'The finish line', 'A type of bicycle'], d: 'hard' },
  { q: 'What colour jersey leads the Tour de France?', a: 'Yellow', pool: ['Green', 'Polka dot', 'White'], d: 'hard' },
  { q: 'In archery, what is the centre of the target worth?', a: 'Ten points', pool: ['Five points', 'Twenty points', 'One point'], d: 'hard' },
  { q: 'What does "LBW" stand for in cricket?', a: 'Leg before wicket', pool: ['Left behind wicket', 'Long ball wide', 'Leg bye wicket'], d: 'hard' },
  { q: 'What is a "safety" worth in American football?', a: 'Two points', pool: ['One point', 'Three points', 'Six points'], d: 'hard' },
  { q: 'How many points is a touchdown worth?', a: 'Six', pool: ['Three', 'Seven', 'Five'], d: 'medium' },
  { q: 'What is a "slam dunk" in basketball?', a: 'Scoring by pushing the ball down through the hoop', pool: ['A three-point shot', 'A blocked shot', 'A free throw'], d: 'easy' },
  { q: 'What is a "free throw" worth in basketball?', a: 'One point', pool: ['Two points', 'Three points', 'Half a point'], d: 'medium' },
  { q: 'What is the term for winning without conceding a goal?', a: 'A clean sheet', pool: ['A shutout only', 'A whitewash', 'A blank'], d: 'hard' },
];
