/**
 * Additional reference rows.
 *
 * The first two tables files proved the approach; this one supplies the volume.
 * Each entry is a single checkable fact that the generators turn into two or
 * three questions.
 */

// ── Physics ─────────────────────────────────────────────────────────────────
export const PHYSICS_FACTS: { q: string; a: string; pool: string[]; d: 'easy' | 'medium' | 'hard' }[] = [
  { q: 'What force pulls objects towards Earth?', a: 'Gravity', pool: ['Magnetism', 'Friction', 'Tension', 'Inertia'], d: 'easy' },
  { q: 'What travels faster, light or sound?', a: 'Light', pool: ['Sound', 'They are equal', 'It depends on colour'], d: 'easy' },
  { q: 'Which state of matter has a fixed shape and volume?', a: 'Solid', pool: ['Liquid', 'Gas', 'Plasma'], d: 'easy' },
  { q: 'What kind of energy does a moving object have?', a: 'Kinetic energy', pool: ['Potential energy', 'Thermal energy', 'Chemical energy'], d: 'easy' },
  { q: 'Which colour of visible light has the longest wavelength?', a: 'Red', pool: ['Violet', 'Green', 'Blue'], d: 'easy' },
  { q: 'What instrument measures temperature?', a: 'A thermometer', pool: ['A barometer', 'An ammeter', 'A hygrometer'], d: 'easy' },
  { q: 'What force opposes motion between surfaces?', a: 'Friction', pool: ['Gravity', 'Inertia', 'Momentum'], d: 'easy' },
  { q: 'Which planet is closest to the Sun?', a: 'Mercury', pool: ['Venus', 'Earth', 'Mars'], d: 'easy' },
  { q: 'What do magnets have at each end?', a: 'Poles', pool: ['Charges', 'Currents', 'Fields only'], d: 'easy' },
  { q: 'Sound cannot travel through what?', a: 'A vacuum', pool: ['Water', 'Steel', 'Air'], d: 'easy' },
  { q: 'What device converts electrical energy into motion?', a: 'A motor', pool: ['A generator', 'A transformer', 'A capacitor'], d: 'easy' },
  { q: 'What do we call energy stored due to position?', a: 'Potential energy', pool: ['Kinetic energy', 'Sound energy', 'Nuclear energy'], d: 'easy' },
  { q: 'Which simple machine is a ramp?', a: 'An inclined plane', pool: ['A lever', 'A pulley', 'A screw'], d: 'easy' },
  { q: 'What is the bending of light between materials called?', a: 'Refraction', pool: ['Reflection', 'Diffraction', 'Absorption'], d: 'easy' },
  { q: 'Which planet is known as the Red Planet?', a: 'Mars', pool: ['Venus', 'Jupiter', 'Mercury'], d: 'easy' },
  { q: 'What is the centre of an atom called?', a: 'The nucleus', pool: ['The electron', 'The orbital', 'The shell'], d: 'easy' },
  { q: 'What happens to most materials when heated?', a: 'They expand', pool: ['They contract', 'They stay the same', 'They become magnetic'], d: 'easy' },
  { q: 'Which type of lens converges light?', a: 'A convex lens', pool: ['A concave lens', 'A plane mirror', 'A prism'], d: 'medium' },
  { q: 'What is the speed of light in a vacuum, approximately?', a: '300,000 km/s', pool: ['300 km/s', '30,000 km/s', '3,000,000 km/s'], d: 'medium' },
  { q: 'What is the acceleration due to gravity on Earth?', a: 'About 9.8 m/s²', pool: ['About 1.6 m/s²', 'About 3.7 m/s²', 'About 11.2 m/s²'], d: 'medium' },
  { q: 'What kind of wave is sound?', a: 'Longitudinal', pool: ['Transverse', 'Electromagnetic', 'Standing only'], d: 'medium' },
  { q: 'What kind of wave is light?', a: 'Transverse', pool: ['Longitudinal', 'Mechanical', 'Compression'], d: 'medium' },
  { q: 'What is the rate of change of velocity called?', a: 'Acceleration', pool: ['Speed', 'Momentum', 'Displacement'], d: 'medium' },
  { q: 'What is momentum equal to?', a: 'Mass times velocity', pool: ['Mass times acceleration', 'Force times distance', 'Half mass times velocity squared'], d: 'medium' },
  { q: 'Which particle has no electric charge?', a: 'The neutron', pool: ['The proton', 'The electron', 'The ion'], d: 'medium' },
  { q: 'What is heat transfer through a moving fluid called?', a: 'Convection', pool: ['Conduction', 'Radiation', 'Insulation'], d: 'medium' },
  { q: 'What is absolute zero in Celsius?', a: '-273.15 °C', pool: ['0 °C', '-100 °C', '-459 °C'], d: 'medium' },
  { q: 'What happens to wavelength as frequency increases?', a: 'It decreases', pool: ['It increases', 'It stays the same', 'It doubles'], d: 'medium' },
  { q: 'What device steps voltage up or down in AC circuits?', a: 'A transformer', pool: ['A resistor', 'A diode', 'A capacitor'], d: 'medium' },
  { q: 'Which particle carries a negative charge?', a: 'The electron', pool: ['The proton', 'The neutron', 'The positron'], d: 'medium' },
  { q: 'What is the term for resistance to a change in motion?', a: 'Inertia', pool: ['Momentum', 'Friction', 'Torque'], d: 'medium' },
  { q: 'Which planet has the most prominent ring system?', a: 'Saturn', pool: ['Jupiter', 'Uranus', 'Neptune'], d: 'medium' },
  { q: 'What is the process of a solid turning straight into gas?', a: 'Sublimation', pool: ['Evaporation', 'Condensation', 'Deposition'], d: 'medium' },
  { q: 'Which mirror type spreads light outwards?', a: 'A convex mirror', pool: ['A concave mirror', 'A plane mirror', 'A parabolic mirror'], d: 'medium' },
  { q: 'What does E = mc² describe?', a: 'The equivalence of mass and energy', pool: ['The force of gravity', 'The speed of sound', 'Conservation of momentum'], d: 'hard' },
  { q: 'Which principle limits knowing position and momentum together?', a: 'The uncertainty principle', pool: ['The exclusion principle', 'The correspondence principle', 'The equivalence principle'], d: 'hard' },
  { q: 'What does the second law of thermodynamics state?', a: 'Entropy increases in an isolated system', pool: ['Energy is conserved', 'Absolute zero is unreachable', 'Pressure and volume are inversely related'], d: 'hard' },
  { q: 'What is light behaving as wave and particle called?', a: 'Wave–particle duality', pool: ['Superposition', 'Entanglement', 'Quantisation'], d: 'hard' },
  { q: 'Which force holds atomic nuclei together?', a: 'The strong nuclear force', pool: ['The weak nuclear force', 'Electromagnetism', 'Gravity'], d: 'hard' },
  { q: 'What is the Doppler effect?', a: 'Observed frequency changing with relative motion', pool: ['Light bending by gravity', 'Light scattering by particles', 'Sound reflecting off surfaces'], d: 'hard' },
  { q: 'Which particle mediates the electromagnetic force?', a: 'The photon', pool: ['The gluon', 'The graviton', 'The W boson'], d: 'hard' },
  { q: 'What is a material with zero electrical resistance called?', a: 'A superconductor', pool: ['A semiconductor', 'An insulator', 'A dielectric'], d: 'hard' },
  { q: 'Which effect emits electrons when light strikes a metal?', a: 'The photoelectric effect', pool: ['The Compton effect', 'The Hall effect', 'The Zeeman effect'], d: 'hard' },
  { q: 'What is escape velocity from Earth, approximately?', a: '11.2 km/s', pool: ['7.8 km/s', '3.0 km/s', '25 km/s'], d: 'hard' },
  { q: 'Which quantity is conserved in an elastic but not inelastic collision?', a: 'Kinetic energy', pool: ['Momentum', 'Mass', 'Charge'], d: 'hard' },
  { q: 'What is half-life?', a: 'Time for half a radioactive sample to decay', pool: ['Time for a wave to half-cycle', 'Half a particle lifetime', 'The midpoint of an orbit'], d: 'hard' },
  { q: 'What is maximum displacement of a wave called?', a: 'Amplitude', pool: ['Wavelength', 'Frequency', 'Period'], d: 'hard' },
  { q: 'Which radiation type is stopped by paper?', a: 'Alpha', pool: ['Beta', 'Gamma', 'X-ray'], d: 'hard' },
  { q: 'What is a magnetic field inducing a current called?', a: 'Electromagnetic induction', pool: ['The photoelectric effect', 'The piezoelectric effect', 'Thermionic emission'], d: 'hard' },
  { q: 'Who developed the theory of general relativity?', a: 'Albert Einstein', pool: ['Isaac Newton', 'Max Planck', 'Werner Heisenberg'], d: 'medium' },
];

// ── History ─────────────────────────────────────────────────────────────────
export const HISTORY_FACTS: { q: string; a: string; pool: string[]; d: 'easy' | 'medium' | 'hard' }[] = [
  { q: 'Who was the first person to walk on the Moon?', a: 'Neil Armstrong', pool: ['Buzz Aldrin', 'Yuri Gagarin', 'Michael Collins'], d: 'easy' },
  { q: 'Which ship sank on its maiden voyage in 1912?', a: 'The Titanic', pool: ['The Lusitania', 'The Britannic', 'The Olympic'], d: 'easy' },
  { q: 'The Renaissance began in which country?', a: 'Italy', pool: ['France', 'England', 'Germany'], d: 'easy' },
  { q: 'Who painted the ceiling of the Sistine Chapel?', a: 'Michelangelo', pool: ['Leonardo da Vinci', 'Raphael', 'Donatello'], d: 'easy' },
  { q: 'Which explorer’s expedition first sailed around the world?', a: 'Ferdinand Magellan', pool: ['Christopher Columbus', 'Vasco da Gama', 'Marco Polo'], d: 'easy' },
  { q: 'Which country was ruled by pharaohs?', a: 'Egypt', pool: ['Greece', 'Persia', 'Rome'], d: 'easy' },
  { q: 'What was the Silk Road used for?', a: 'Trade between Asia and Europe', pool: ['Military defence', 'Religious pilgrimage only', 'Royal processions'], d: 'easy' },
  { q: 'Which ancient people built the Parthenon?', a: 'The Greeks', pool: ['The Romans', 'The Persians', 'The Egyptians'], d: 'easy' },
  { q: 'In which country did the Samurai serve?', a: 'Japan', pool: ['China', 'Korea', 'Mongolia'], d: 'easy' },
  { q: 'Who was the Egyptian queen famous for her alliance with Rome?', a: 'Cleopatra', pool: ['Nefertiti', 'Hatshepsut', 'Boudicca'], d: 'easy' },
  { q: 'Which war was fought between the North and South of the USA?', a: 'The American Civil War', pool: ['The War of 1812', 'The Revolutionary War', 'The Mexican War'], d: 'easy' },
  { q: 'Which empire was centred on Constantinople after Rome fell?', a: 'The Byzantine Empire', pool: ['The Ottoman Empire', 'The Persian Empire', 'The Holy Roman Empire'], d: 'medium' },
  { q: 'Which treaty ended World War I?', a: 'The Treaty of Versailles', pool: ['The Treaty of Ghent', 'The Treaty of Utrecht', 'The Treaty of Tordesillas'], d: 'medium' },
  { q: 'Who was the first female Prime Minister of the UK?', a: 'Margaret Thatcher', pool: ['Theresa May', 'Liz Truss', 'Barbara Castle'], d: 'medium' },
  { q: 'Which civilisation built Machu Picchu?', a: 'The Inca', pool: ['The Maya', 'The Aztec', 'The Olmec'], d: 'medium' },
  { q: 'Which document limited the power of the English king in 1215?', a: 'Magna Carta', pool: ['The Bill of Rights', 'The Domesday Book', 'The Petition of Right'], d: 'medium' },
  { q: 'What was the Cold War primarily between?', a: 'The USA and the Soviet Union', pool: ['Britain and France', 'China and India', 'Germany and Poland'], d: 'medium' },
  { q: 'Which invention did Gutenberg develop?', a: 'The printing press', pool: ['The steam engine', 'The telescope', 'The compass'], d: 'medium' },
  { q: 'Who led the Soviet Union during most of World War II?', a: 'Joseph Stalin', pool: ['Vladimir Lenin', 'Nikita Khrushchev', 'Leon Trotsky'], d: 'medium' },
  { q: 'Which war ended with the Treaty of Ghent?', a: 'The War of 1812', pool: ['The American Civil War', 'The Revolutionary War', 'The Seven Years War'], d: 'hard' },
  { q: 'Which dynasty built most of the surviving Great Wall?', a: 'The Ming', pool: ['The Han', 'The Tang', 'The Qing'], d: 'hard' },
  { q: 'Who was the first Roman Emperor?', a: 'Augustus', pool: ['Julius Caesar', 'Nero', 'Tiberius'], d: 'hard' },
  { q: 'Which country was formerly called Ceylon?', a: 'Sri Lanka', pool: ['Myanmar', 'Thailand', 'Bangladesh'], d: 'hard' },
  { q: 'Which revolution overthrew the Qing dynasty?', a: 'The Xinhai Revolution', pool: ['The Boxer Rebellion', 'The Cultural Revolution', 'The Taiping Rebellion'], d: 'hard' },
  { q: 'Hannibal crossed which mountain range with elephants?', a: 'The Alps', pool: ['The Pyrenees', 'The Apennines', 'The Atlas Mountains'], d: 'hard' },
  { q: 'Which empire did Suleiman the Magnificent rule?', a: 'The Ottoman Empire', pool: ['The Mughal Empire', 'The Safavid Empire', 'The Byzantine Empire'], d: 'hard' },
  { q: 'Who was the last Tsar of Russia?', a: 'Nicholas II', pool: ['Alexander III', 'Peter III', 'Paul I'], d: 'hard' },
  { q: 'Which US president oversaw the Louisiana Purchase?', a: 'Thomas Jefferson', pool: ['James Madison', 'John Adams', 'James Monroe'], d: 'hard' },
  { q: 'Which ancient wonder stood at Alexandria?', a: 'The Lighthouse', pool: ['The Hanging Gardens', 'The Colossus', 'The Mausoleum'], d: 'hard' },
  { q: 'The Domesday Book was ordered by which king?', a: 'William the Conqueror', pool: ['Henry VIII', 'Richard I', 'Edward the Confessor'], d: 'hard' },
];

// ── Sports ──────────────────────────────────────────────────────────────────
export const SPORT_FACTS: { q: string; a: string; pool: string[]; d: 'easy' | 'medium' | 'hard' }[] = [
  { q: 'Which sport uses a shuttlecock?', a: 'Badminton', pool: ['Tennis', 'Squash', 'Table tennis'], d: 'easy' },
  { q: 'In swimming, which stroke is swum on the back?', a: 'Backstroke', pool: ['Freestyle', 'Butterfly', 'Breaststroke'], d: 'easy' },
  { q: 'What surface is Wimbledon played on?', a: 'Grass', pool: ['Clay', 'Hard court', 'Carpet'], d: 'easy' },
  { q: 'Which sport has innings?', a: 'Baseball', pool: ['Football', 'Rugby', 'Hockey'], d: 'easy' },
  { q: 'What do you call the person who enforces rules in football?', a: 'The referee', pool: ['The umpire', 'The judge', 'The marshal'], d: 'easy' },
  { q: 'Which sport is played on a diamond?', a: 'Baseball', pool: ['Cricket', 'Softball only', 'Lacrosse'], d: 'easy' },
  { q: 'How many points is a standard basketball field goal worth?', a: 'Two', pool: ['One', 'Three', 'Four'], d: 'easy' },
  { q: 'Which sport features the Tour de France?', a: 'Cycling', pool: ['Running', 'Motor racing', 'Rowing'], d: 'easy' },
  { q: 'In cricket, what dismisses a batter caught behind?', a: 'A catch by the wicketkeeper', pool: ['A run out', 'An LBW', 'A stumping'], d: 'medium' },
  { q: 'Which Olympic event combines swimming, cycling and running?', a: 'The triathlon', pool: ['The pentathlon', 'The decathlon', 'The heptathlon'], d: 'medium' },
  { q: 'How many events are in a decathlon?', a: 'Ten', pool: ['Seven', 'Five', 'Twelve'], d: 'medium' },
  { q: 'Which sport uses the term "checkmate"?', a: 'Chess', pool: ['Draughts', 'Backgammon', 'Go'], d: 'medium' },
  { q: 'What is the height of a tennis net at the centre?', a: 'About 3 feet', pool: ['About 2 feet', 'About 4 feet', 'About 5 feet'], d: 'medium' },
  { q: 'In rugby, what restarts play after a minor infringement?', a: 'A scrum', pool: ['A lineout', 'A penalty', 'A conversion'], d: 'medium' },
  { q: 'How many players are on an ice hockey team on the ice?', a: 'Six', pool: ['Five', 'Seven', 'Four'], d: 'medium' },
  { q: 'What is the term for scoring three goals in one match?', a: 'A hat-trick', pool: ['A treble', 'A triple', 'A trifecta'], d: 'medium' },
  { q: 'Which sport awards the Ryder Cup?', a: 'Golf', pool: ['Tennis', 'Sailing', 'Rowing'], d: 'medium' },
  { q: 'What is the standard length of an Olympic pool?', a: '50 metres', pool: ['25 metres', '100 metres', '75 metres'], d: 'medium' },
  { q: 'In fencing, what is the target area for foil?', a: 'The torso', pool: ['The whole body', 'Above the waist', 'The legs only'], d: 'hard' },
  { q: 'What is a "nutmeg" in football?', a: 'Playing the ball through an opponent’s legs', pool: ['A curved free kick', 'A diving header', 'A sliding tackle'], d: 'hard' },
  { q: 'How many squares are on a Snakes and Ladders board traditionally?', a: '100', pool: ['64', '81', '144'], d: 'hard' },
  { q: 'In golf, what is one under par called?', a: 'A birdie', pool: ['An eagle', 'A bogey', 'An albatross'], d: 'hard' },
  { q: 'Which country hosted the first modern Olympic Games?', a: 'Greece', pool: ['France', 'Britain', 'Italy'], d: 'hard' },
  { q: 'What is the maximum score in a single game of ten-pin bowling?', a: '300', pool: ['200', '250', '270'], d: 'hard' },
  { q: 'In cricket, what is a score of zero by a batter called?', a: 'A duck', pool: ['A blank', 'A love', 'A nil'], d: 'hard' },
  { q: 'What weight class is directly above featherweight in boxing?', a: 'Lightweight', pool: ['Bantamweight', 'Welterweight', 'Middleweight'], d: 'hard' },
];

// ── Technology ──────────────────────────────────────────────────────────────
export const TECH_FACTS: { q: string; a: string; pool: string[]; d: 'easy' | 'medium' | 'hard' }[] = [
  { q: 'What is the most common way to connect to the internet wirelessly?', a: 'Wi-Fi', pool: ['Ethernet', 'Bluetooth', 'Infrared'], d: 'easy' },
  { q: 'Which part of a computer displays images?', a: 'The monitor', pool: ['The keyboard', 'The CPU', 'The router'], d: 'easy' },
  { q: 'What does a web browser do?', a: 'Displays web pages', pool: ['Stores files', 'Prints documents', 'Cools the computer'], d: 'easy' },
  { q: 'What is a common shortcut to paste?', a: 'Ctrl+V', pool: ['Ctrl+C', 'Ctrl+X', 'Ctrl+P'], d: 'easy' },
  { q: 'What does "download" mean?', a: 'Transferring data to your device', pool: ['Sending data away', 'Deleting data', 'Encrypting data'], d: 'easy' },
  { q: 'Which device connects a home network to the internet?', a: 'A router', pool: ['A monitor', 'A printer', 'A scanner'], d: 'easy' },
  { q: 'What is software that harms a computer called?', a: 'Malware', pool: ['Firmware', 'Freeware', 'Middleware'], d: 'easy' },
  { q: 'What does a search engine do?', a: 'Finds pages matching a query', pool: ['Stores your files', 'Blocks adverts', 'Speeds up your CPU'], d: 'easy' },
  { q: 'What is the most widely used desktop operating system?', a: 'Windows', pool: ['Linux', 'ChromeOS', 'FreeBSD'], d: 'easy' },
  { q: 'What does "wireless charging" avoid needing?', a: 'A cable', pool: ['A battery', 'Electricity', 'A power source'], d: 'easy' },
  { q: 'What does encryption do to data?', a: 'Makes it unreadable without a key', pool: ['Compresses it', 'Deletes it', 'Duplicates it'], d: 'medium' },
  { q: 'What is a megabyte roughly equal to?', a: 'A thousand kilobytes', pool: ['A thousand gigabytes', 'A million gigabytes', 'A hundred bytes'], d: 'medium' },
  { q: 'What is machine learning a subset of?', a: 'Artificial intelligence', pool: ['Cloud computing', 'Cybersecurity', 'Networking'], d: 'medium' },
  { q: 'What does a database primarily do?', a: 'Stores and organises data', pool: ['Renders graphics', 'Manages power', 'Compresses video'], d: 'medium' },
  { q: 'What is the purpose of a cache?', a: 'To store data for faster access', pool: ['To encrypt data', 'To delete old files', 'To connect networks'], d: 'medium' },
  { q: 'What does "two-factor authentication" add?', a: 'A second proof of identity', pool: ['A second password only', 'A faster login', 'A backup account'], d: 'medium' },
  { q: 'What is an algorithm?', a: 'A step-by-step procedure to solve a problem', pool: ['A type of hardware', 'A programming language', 'A network protocol'], d: 'medium' },
  { q: 'What does a version control system track?', a: 'Changes to files over time', pool: ['Network traffic', 'CPU temperature', 'Screen resolution'], d: 'medium' },
  { q: 'What is latency in networking?', a: 'The delay before data transfers', pool: ['The amount of data sent', 'The number of devices', 'The cable length'], d: 'medium' },
  { q: 'What is the purpose of a load balancer?', a: 'Distributing traffic across servers', pool: ['Encrypting traffic', 'Storing backups', 'Compressing images'], d: 'hard' },
  { q: 'What is a hash function used for?', a: 'Producing a fixed-size fingerprint of data', pool: ['Encrypting reversibly', 'Compressing files', 'Sorting arrays'], d: 'hard' },
  { q: 'In Big-O notation, which is fastest for large inputs?', a: 'O(log n)', pool: ['O(n)', 'O(n²)', 'O(2ⁿ)'], d: 'hard' },
  { q: 'What does "idempotent" mean for an API request?', a: 'Repeating it has the same effect as once', pool: ['It always fails safely', 'It runs asynchronously', 'It requires no auth'], d: 'hard' },
  { q: 'What is a race condition?', a: 'A bug where timing changes the outcome', pool: ['A slow network request', 'A memory leak', 'A syntax error'], d: 'hard' },
  { q: 'What does TCP guarantee that UDP does not?', a: 'Ordered, reliable delivery', pool: ['Faster transfer', 'Encryption', 'Lower latency'], d: 'hard' },
  { q: 'What is the purpose of an index in a database?', a: 'Speeding up lookups', pool: ['Saving disk space', 'Encrypting rows', 'Backing up tables'], d: 'hard' },
];

// ── Food & Cooking ──────────────────────────────────────────────────────────
export const FOOD_FACTS: { q: string; a: string; pool: string[]; d: 'easy' | 'medium' | 'hard' }[] = [
  { q: 'Which fruit is traditionally used to make cider?', a: 'Apple', pool: ['Pear', 'Grape', 'Peach'], d: 'easy' },
  { q: 'What is the main ingredient in hummus?', a: 'Chickpeas', pool: ['Lentils', 'Beans', 'Peas'], d: 'easy' },
  { q: 'Which meat is traditionally in a Bolognese sauce?', a: 'Beef', pool: ['Chicken', 'Lamb', 'Fish'], d: 'easy' },
  { q: 'What kind of food is a baguette?', a: 'Bread', pool: ['Cheese', 'Pastry', 'Soup'], d: 'easy' },
  { q: 'Which fruit is dried to make a prune?', a: 'Plum', pool: ['Grape', 'Date', 'Fig'], d: 'easy' },
  { q: 'What is the main ingredient in traditional pesto?', a: 'Basil', pool: ['Parsley', 'Mint', 'Coriander'], d: 'easy' },
  { q: 'Which drink is made by fermenting grapes?', a: 'Wine', pool: ['Beer', 'Cider', 'Sake'], d: 'easy' },
  { q: 'What part of the plant is a carrot?', a: 'The root', pool: ['The stem', 'The leaf', 'The fruit'], d: 'easy' },
  { q: 'Which grain is used to make sake?', a: 'Rice', pool: ['Barley', 'Wheat', 'Corn'], d: 'medium' },
  { q: 'What makes bread dough rise?', a: 'Carbon dioxide from yeast', pool: ['Oxygen from mixing', 'Steam from water', 'Nitrogen from flour'], d: 'medium' },
  { q: 'What is the primary flavour in a classic pesto?', a: 'Basil and garlic', pool: ['Tomato and onion', 'Lemon and dill', 'Chilli and cumin'], d: 'medium' },
  { q: 'Which cooking method uses dry heat in an oven?', a: 'Roasting', pool: ['Boiling', 'Steaming', 'Poaching'], d: 'medium' },
  { q: 'What is the difference between jam and jelly?', a: 'Jelly is made from juice only', pool: ['Jam has no sugar', 'Jelly is savoury', 'Jam is never cooked'], d: 'medium' },
  { q: 'Which dairy product is made by churning cream?', a: 'Butter', pool: ['Cheese', 'Yoghurt', 'Cream cheese'], d: 'medium' },
  { q: 'What temperature is considered a "low and slow" roast?', a: 'Around 120–150 °C', pool: ['Around 220 °C', 'Around 250 °C', 'Around 90 °C'], d: 'medium' },
  { q: 'Which vitamin is destroyed most by overcooking vegetables?', a: 'Vitamin C', pool: ['Vitamin D', 'Vitamin K', 'Vitamin E'], d: 'hard' },
  { q: 'What does "proving" dough mean?', a: 'Letting it rise before baking', pool: ['Testing its temperature', 'Rolling it flat', 'Chilling it overnight'], d: 'hard' },
  { q: 'Which knife cut produces small even cubes?', a: 'A brunoise', pool: ['A chiffonade', 'A batonnet', 'A rondelle'], d: 'hard' },
  { q: 'What is a roux made from?', a: 'Fat and flour', pool: ['Egg and cream', 'Stock and wine', 'Butter and sugar'], d: 'hard' },
  { q: 'Why is salt added to pasta water?', a: 'To season the pasta itself', pool: ['To make it boil faster', 'To stop sticking', 'To soften the water'], d: 'hard' },
  { q: 'What does "deglaze" mean?', a: 'Adding liquid to lift browned bits from a pan', pool: ['Removing fat from stock', 'Coating in glaze', 'Chilling a sauce'], d: 'hard' },
];

// ── Pop Culture ─────────────────────────────────────────────────────────────
export const POP_FACTS: { q: string; a: string; pool: string[]; d: 'easy' | 'medium' | 'hard' }[] = [
  { q: 'How many players are in a standard string quartet?', a: 'Four', pool: ['Three', 'Five', 'Six'], d: 'easy' },
  { q: 'Which instrument family does the trumpet belong to?', a: 'Brass', pool: ['Woodwind', 'Strings', 'Percussion'], d: 'easy' },
  { q: 'What is the art of beautiful handwriting called?', a: 'Calligraphy', pool: ['Typography', 'Lithography', 'Origami'], d: 'easy' },
  { q: 'What is a story passed down orally called?', a: 'A folk tale', pool: ['A memoir', 'A treatise', 'A manifesto'], d: 'easy' },
  { q: 'Which Japanese art form involves folding paper?', a: 'Origami', pool: ['Ikebana', 'Kabuki', 'Bonsai'], d: 'easy' },
  { q: 'What is the main instrument in a piano concerto?', a: 'The piano', pool: ['The violin', 'The cello', 'The flute'], d: 'easy' },
  { q: 'Which theatre tradition uses elaborate masks in Japan?', a: 'Noh', pool: ['Kabuki', 'Bunraku', 'Rakugo'], d: 'medium' },
  { q: 'What is the term for a book written about oneself?', a: 'An autobiography', pool: ['A biography', 'A novella', 'An anthology'], d: 'medium' },
  { q: 'What does "genre" mean?', a: 'A category of artistic work', pool: ['An artistic technique', 'A creative period', 'A style of writing only'], d: 'medium' },
  { q: 'Which colour scheme uses opposite colours on the wheel?', a: 'Complementary', pool: ['Analogous', 'Monochromatic', 'Triadic'], d: 'medium' },
  { q: 'What is a soliloquy?', a: 'A character speaking their thoughts aloud alone', pool: ['A duet between characters', 'A stage direction', 'A change of scene'], d: 'medium' },
  { q: 'Which art form is Ansel Adams known for?', a: 'Photography', pool: ['Sculpture', 'Painting', 'Printmaking'], d: 'medium' },
  { q: 'What does "avant-garde" describe?', a: 'Experimental or innovative work', pool: ['Traditional work', 'Commercial work', 'Religious work'], d: 'medium' },
  { q: 'What is the study of film called?', a: 'Cinematography or film studies', pool: ['Choreography', 'Cartography', 'Chronology'], d: 'medium' },
  { q: 'Which musical term means very loud?', a: 'Fortissimo', pool: ['Pianissimo', 'Moderato', 'Andante'], d: 'hard' },
  { q: 'What is a bildungsroman?', a: 'A coming-of-age novel', pool: ['A crime novel', 'An epic poem', 'A stage tragedy'], d: 'hard' },
  { q: 'Which architectural style features pointed arches and flying buttresses?', a: 'Gothic', pool: ['Romanesque', 'Baroque', 'Neoclassical'], d: 'hard' },
  { q: 'What is the term for painting on wet plaster?', a: 'Fresco', pool: ['Tempera', 'Gouache', 'Encaustic'], d: 'hard' },
  { q: 'In music, what is an interval of eight notes called?', a: 'An octave', pool: ['A fifth', 'A third', 'A seventh'], d: 'hard' },
  { q: 'What is iambic pentameter?', a: 'Five pairs of unstressed-stressed syllables', pool: ['Ten rhyming lines', 'Five rhyming couplets', 'A four-beat rhythm'], d: 'hard' },
  { q: 'Which movement followed Impressionism?', a: 'Post-Impressionism', pool: ['Romanticism', 'Realism', 'Baroque'], d: 'hard' },
];

// ── Biology extras ──────────────────────────────────────────────────────────
export const BIOLOGY_FACTS: { q: string; a: string; pool: string[]; d: 'easy' | 'medium' | 'hard' }[] = [
  { q: 'What do plants need from the Sun?', a: 'Light for photosynthesis', pool: ['Heat for growth only', 'Radio waves', 'Gravity'], d: 'easy' },
  { q: 'Which animal is the fastest on land?', a: 'The cheetah', pool: ['The lion', 'The horse', 'The greyhound'], d: 'easy' },
  { q: 'What do we call an animal that eats both plants and meat?', a: 'An omnivore', pool: ['A herbivore', 'A carnivore', 'An insectivore'], d: 'easy' },
  { q: 'Which part of a flower makes pollen?', a: 'The anther', pool: ['The stigma', 'The petal', 'The sepal'], d: 'medium' },
  { q: 'How many legs does a spider have?', a: 'Eight', pool: ['Six', 'Ten', 'Twelve'], d: 'easy' },
  { q: 'Which gas do humans need to breathe?', a: 'Oxygen', pool: ['Carbon dioxide', 'Nitrogen', 'Helium'], d: 'easy' },
  { q: 'What is the largest species of big cat?', a: 'The tiger', pool: ['The lion', 'The jaguar', 'The leopard'], d: 'easy' },
  { q: 'Which animal produces wool?', a: 'The sheep', pool: ['The goat', 'The cow', 'The pig'], d: 'easy' },
  { q: 'What is a young frog called before it grows legs?', a: 'A tadpole', pool: ['A nymph', 'A larva only', 'A fry'], d: 'easy' },
  { q: 'Which sense do bats use most to navigate in the dark?', a: 'Echolocation', pool: ['Smell', 'Sight', 'Touch'], d: 'medium' },
  { q: 'What is the term for an animal that has died out entirely?', a: 'Extinct', pool: ['Endangered', 'Dormant', 'Migratory'], d: 'easy' },
  { q: 'Which organ system moves blood around the body?', a: 'The circulatory system', pool: ['The digestive system', 'The nervous system', 'The skeletal system'], d: 'easy' },
  { q: 'What is a food chain?', a: 'A sequence of who eats whom', pool: ['A list of nutrients', 'A type of habitat', 'A breeding pattern'], d: 'medium' },
  { q: 'What is the term for animals that sleep through winter?', a: 'Hibernation', pool: ['Migration', 'Aestivation', 'Torpor only'], d: 'medium' },
  { q: 'Which structure carries genetic material in a cell?', a: 'The chromosome', pool: ['The ribosome', 'The vacuole', 'The lysosome'], d: 'medium' },
  { q: 'What is symbiosis?', a: 'A close relationship between two species', pool: ['Competition for food', 'A form of migration', 'A method of reproduction'], d: 'hard' },
  { q: 'What does an ecosystem consist of?', a: 'Living things and their environment', pool: ['Only the animals', 'Only the plants', 'Only the climate'], d: 'medium' },
  { q: 'Which blood component helps wounds clot?', a: 'Platelets', pool: ['Red blood cells', 'Plasma', 'White blood cells'], d: 'medium' },
];
