/**
 * General Knowledge's own material.
 *
 * Deliberately drawn from areas no other category generates — language, time
 * and the calendar, measurement, symbols, everyday objects and conventions —
 * so the cross-category dedupe never has to choose between two files.
 */
type F = { q: string; a: string; pool: string[]; d: 'easy' | 'medium' | 'hard' };

export const GK: F[] = [
  // Calendar and time
  { q: 'How many days are in a leap year?', a: '366', pool: ['365', '364', '367'], d: 'easy' },
  { q: 'How many months have 31 days?', a: 'Seven', pool: ['Six', 'Five', 'Eight'], d: 'easy' },
  { q: 'Which month has the fewest days?', a: 'February', pool: ['April', 'June', 'November'], d: 'easy' },
  { q: 'How many hours are in two days?', a: '48', pool: ['24', '36', '72'], d: 'easy' },
  { q: 'How many minutes are in three hours?', a: '180', pool: ['120', '150', '240'], d: 'easy' },
  { q: 'How many seconds are in five minutes?', a: '300', pool: ['250', '360', '500'], d: 'easy' },
  { q: 'What is the first month of the year?', a: 'January', pool: ['December', 'March', 'February'], d: 'easy' },
  { q: 'What is the last month of the year?', a: 'December', pool: ['November', 'January', 'October'], d: 'easy' },
  { q: 'How many weeks are in a year, approximately?', a: '52', pool: ['48', '56', '60'], d: 'easy' },
  { q: 'How many days are in a fortnight?', a: '14', pool: ['7', '10', '21'], d: 'easy' },
  { q: 'What does "AM" mean on a clock?', a: 'Before noon', pool: ['After noon', 'At midnight', 'All morning'], d: 'easy' },
  { q: 'How often does a leap year occur?', a: 'Every four years', pool: ['Every two years', 'Every five years', 'Every ten years'], d: 'easy' },
  { q: 'Which day follows Wednesday?', a: 'Thursday', pool: ['Tuesday', 'Friday', 'Monday'], d: 'easy' },
  { q: 'How many days are in September?', a: '30', pool: ['31', '29', '28'], d: 'easy' },
  { q: 'What is midday also called?', a: 'Noon', pool: ['Midnight', 'Dusk', 'Dawn'], d: 'easy' },
  { q: 'Which calendar is most widely used today?', a: 'The Gregorian calendar', pool: ['The Julian calendar', 'The lunar calendar', 'The Hebrew calendar'], d: 'medium' },
  { q: 'What is the international standard for coordinated time called?', a: 'UTC', pool: ['GMT+1', 'EST', 'IST'], d: 'medium' },
  { q: 'What is a "decade" in years?', a: 'Ten', pool: ['Five', 'Twenty', 'Hundred'], d: 'easy' },

  // Measurement and numbers
  { q: 'How many centimetres are in a metre?', a: '100', pool: ['10', '1000', '50'], d: 'easy' },
  { q: 'How many metres are in a kilometre?', a: '1000', pool: ['100', '10000', '500'], d: 'easy' },
  { q: 'How many grams are in a kilogram?', a: '1000', pool: ['100', '10', '10000'], d: 'easy' },
  { q: 'How many millilitres are in a litre?', a: '1000', pool: ['100', '10', '500'], d: 'easy' },
  { q: 'How many sides does a triangle have?', a: 'Three', pool: ['Four', 'Five', 'Two'], d: 'easy' },
  { q: 'How many sides does a hexagon have?', a: 'Six', pool: ['Five', 'Seven', 'Eight'], d: 'easy' },
  { q: 'How many sides does an octagon have?', a: 'Eight', pool: ['Six', 'Seven', 'Ten'], d: 'easy' },
  { q: 'How many sides does a pentagon have?', a: 'Five', pool: ['Four', 'Six', 'Seven'], d: 'easy' },
  { q: 'How many degrees are in a right angle?', a: '90', pool: ['45', '180', '360'], d: 'easy' },
  { q: 'How many degrees are in a full circle?', a: '360', pool: ['180', '270', '400'], d: 'easy' },
  { q: 'What is half of 100?', a: '50', pool: ['25', '75', '10'], d: 'easy' },
  { q: 'What is a quarter of 100?', a: '25', pool: ['50', '20', '40'], d: 'easy' },
  { q: 'How many zeros are in a million?', a: 'Six', pool: ['Five', 'Seven', 'Nine'], d: 'easy' },
  { q: 'How many zeros are in a billion (short scale)?', a: 'Nine', pool: ['Six', 'Twelve', 'Eight'], d: 'medium' },
  { q: 'What is a dozen?', a: 'Twelve', pool: ['Ten', 'Twenty', 'Six'], d: 'easy' },
  { q: 'What is a "score" as a number?', a: 'Twenty', pool: ['Ten', 'Fifty', 'Twelve'], d: 'medium' },
  { q: 'What is the Roman numeral for 10?', a: 'X', pool: ['V', 'L', 'C'], d: 'easy' },
  { q: 'What is the Roman numeral for 50?', a: 'L', pool: ['X', 'C', 'D'], d: 'medium' },
  { q: 'What is the Roman numeral for 100?', a: 'C', pool: ['L', 'D', 'M'], d: 'medium' },
  { q: 'What is the Roman numeral for 1000?', a: 'M', pool: ['C', 'D', 'X'], d: 'medium' },
  { q: 'How many inches are in a foot?', a: '12', pool: ['10', '16', '36'], d: 'medium' },
  { q: 'How many feet are in a yard?', a: 'Three', pool: ['Two', 'Four', 'Six'], d: 'medium' },
  { q: 'What is the value of pi to two decimal places?', a: '3.14', pool: ['3.41', '3.12', '3.16'], d: 'medium' },
  { q: 'What is an even number divisible by?', a: 'Two', pool: ['Three', 'Five', 'Seven'], d: 'easy' },
  { q: 'What is a prime number?', a: 'One divisible only by itself and 1', pool: ['Any odd number', 'Any even number', 'A number ending in 1'], d: 'medium' },

  // Language and words
  { q: 'How many letters are in the English alphabet?', a: '26', pool: ['24', '25', '28'], d: 'easy' },
  { q: 'How many vowels are in the English alphabet?', a: 'Five', pool: ['Four', 'Six', 'Three'], d: 'easy' },
  { q: 'What is a word with the same meaning as another called?', a: 'A synonym', pool: ['An antonym', 'A homonym', 'An acronym'], d: 'easy' },
  { q: 'What is a word with the opposite meaning called?', a: 'An antonym', pool: ['A synonym', 'A homonym', 'A pronoun'], d: 'easy' },
  { q: 'What is a word formed from initials called?', a: 'An acronym', pool: ['A synonym', 'An antonym', 'A homonym'], d: 'easy' },
  { q: 'What is a describing word called in grammar?', a: 'An adjective', pool: ['A noun', 'A verb', 'An adverb'], d: 'easy' },
  { q: 'What is an action word called in grammar?', a: 'A verb', pool: ['A noun', 'An adjective', 'A preposition'], d: 'easy' },
  { q: 'What is a naming word called in grammar?', a: 'A noun', pool: ['A verb', 'An adverb', 'A conjunction'], d: 'easy' },
  { q: 'What is a word that replaces a noun called?', a: 'A pronoun', pool: ['An adverb', 'An adjective', 'An article'], d: 'medium' },
  { q: 'What is a word that describes a verb called?', a: 'An adverb', pool: ['An adjective', 'A noun', 'A pronoun'], d: 'medium' },
  { q: 'What punctuation ends a question?', a: 'A question mark', pool: ['A full stop', 'A comma', 'A colon'], d: 'easy' },
  { q: 'What punctuation shows strong feeling?', a: 'An exclamation mark', pool: ['A comma', 'A semicolon', 'A hyphen'], d: 'easy' },
  { q: 'What punctuation shows possession?', a: 'An apostrophe', pool: ['A comma', 'A hyphen', 'A colon'], d: 'easy' },
  { q: 'What marks are used around direct speech?', a: 'Quotation marks', pool: ['Brackets', 'Dashes', 'Asterisks'], d: 'easy' },
  { q: 'What is a shortened form like "don\'t" called?', a: 'A contraction', pool: ['An abbreviation', 'An acronym', 'An initialism'], d: 'medium' },
  { q: 'What is the plural of "child"?', a: 'Children', pool: ['Childs', 'Childes', 'Childrens'], d: 'easy' },
  { q: 'What is the plural of "mouse" (the animal)?', a: 'Mice', pool: ['Mouses', 'Mices', 'Mouse'], d: 'easy' },
  { q: 'What is the plural of "goose"?', a: 'Geese', pool: ['Gooses', 'Geeses', 'Goosen'], d: 'easy' },
  { q: 'What is a phrase whose meaning is not literal called?', a: 'An idiom', pool: ['A simile', 'A synonym', 'A clause'], d: 'medium' },
  { q: 'What is a word that sounds the same but is spelt differently?', a: 'A homophone', pool: ['A synonym', 'An antonym', 'An acronym'], d: 'medium' },
  { q: 'What is the study of word origins called?', a: 'Etymology', pool: ['Entomology', 'Ecology', 'Epidemiology'], d: 'hard' },
  { q: 'What is a book of word meanings called?', a: 'A dictionary', pool: ['An atlas', 'An almanac', 'A directory'], d: 'easy' },
  { q: 'What is a book of synonyms called?', a: 'A thesaurus', pool: ['A dictionary', 'A glossary', 'An index'], d: 'medium' },
  { q: 'What is a book of maps called?', a: 'An atlas', pool: ['A dictionary', 'A thesaurus', 'An almanac'], d: 'easy' },
  { q: 'What is an alphabetical list at the back of a book called?', a: 'An index', pool: ['A glossary', 'A preface', 'An appendix'], d: 'medium' },
  { q: 'What is a list of terms and definitions in a book called?', a: 'A glossary', pool: ['An index', 'A bibliography', 'A foreword'], d: 'medium' },
  { q: 'What is a list of sources at the end of a work called?', a: 'A bibliography', pool: ['An index', 'A glossary', 'An abstract'], d: 'medium' },
  { q: 'Which language has the most native speakers?', a: 'Mandarin Chinese', pool: ['English', 'Spanish', 'Hindi'], d: 'medium' },
  { q: 'Which alphabet is used to write Russian?', a: 'Cyrillic', pool: ['Latin', 'Greek', 'Arabic'], d: 'medium' },
  { q: 'Which direction is Arabic written in?', a: 'Right to left', pool: ['Left to right', 'Top to bottom', 'Bottom to top'], d: 'medium' },
  { q: 'What is Braille used for?', a: 'Reading by touch', pool: ['Reading by sound', 'Writing shorthand', 'Encrypting text'], d: 'easy' },
  { q: 'What is Morse code made of?', a: 'Dots and dashes', pool: ['Numbers only', 'Letters only', 'Colours'], d: 'easy' },
  { q: 'What does "SOS" signal?', a: 'Distress', pool: ['All clear', 'Arrival', 'Departure'], d: 'easy' },

  // Everyday facts, symbols and conventions
  { q: 'What colour means "stop" on a traffic light?', a: 'Red', pool: ['Green', 'Amber', 'Blue'], d: 'easy' },
  { q: 'What colour means "go" on a traffic light?', a: 'Green', pool: ['Red', 'Amber', 'White'], d: 'easy' },
  { q: 'What shape is a standard stop sign?', a: 'An octagon', pool: ['A triangle', 'A circle', 'A square'], d: 'medium' },
  { q: 'What does a red cross on white usually indicate?', a: 'Medical help', pool: ['A police station', 'A fire exit', 'A school'], d: 'easy' },
  { q: 'What colour is a standard fire engine in most countries?', a: 'Red', pool: ['Blue', 'Yellow', 'Green'], d: 'easy' },
  { q: 'Which number do you dial for emergencies in the UK?', a: '999', pool: ['911', '112 only', '000'], d: 'medium' },
  { q: 'Which number do you dial for emergencies in the USA?', a: '911', pool: ['999', '112', '000'], d: 'medium' },
  { q: 'What does a barcode store?', a: 'Product information', pool: ['A price only', 'A photograph', 'A password'], d: 'easy' },
  { q: 'What is a passport used for?', a: 'International travel identification', pool: ['Driving a car', 'Opening a bank account only', 'Voting'], d: 'easy' },
  { q: 'What does a compass needle point towards?', a: 'Magnetic north', pool: ['True south', 'The nearest city', 'The Sun'], d: 'easy' },
  { q: 'How many sides does a standard die have?', a: 'Six', pool: ['Four', 'Eight', 'Twelve'], d: 'easy' },
  { q: 'How many cards are in a standard deck without jokers?', a: '52', pool: ['48', '54', '60'], d: 'easy' },
  { q: 'How many suits are in a deck of cards?', a: 'Four', pool: ['Two', 'Three', 'Five'], d: 'easy' },
  { q: 'How many squares are on a chessboard?', a: '64', pool: ['36', '81', '100'], d: 'medium' },
  { q: 'How many pieces does each player start with in chess?', a: '16', pool: ['12', '20', '8'], d: 'medium' },
  { q: 'How many dots are on a standard domino set’s highest tile?', a: 'Twelve', pool: ['Six', 'Nine', 'Eighteen'], d: 'hard' },
  { q: 'How many keys are on a standard traffic pedestrian crossing button?', a: 'One', pool: ['Two', 'Three', 'Four'], d: 'easy' },
  { q: 'What are the colours of a standard chessboard?', a: 'Light and dark', pool: ['Red and blue', 'Green and yellow', 'All one colour'], d: 'easy' },
  { q: 'What does a wedding ring traditionally symbolise?', a: 'Marriage', pool: ['Wealth', 'Rank', 'Membership'], d: 'easy' },
  { q: 'What is the currency symbol "£"?', a: 'Pound', pool: ['Euro', 'Yen', 'Dollar'], d: 'easy' },
  { q: 'What is the currency symbol "€"?', a: 'Euro', pool: ['Pound', 'Dollar', 'Franc'], d: 'easy' },
  { q: 'What is the currency symbol "¥"?', a: 'Yen', pool: ['Won', 'Rupee', 'Yuan only'], d: 'medium' },
  { q: 'What is the currency of the United Kingdom?', a: 'The pound sterling', pool: ['The euro', 'The dollar', 'The franc'], d: 'easy' },
  { q: 'What does "www" stand for in a web address?', a: 'World Wide Web', pool: ['Wide World Web', 'World Web Wire', 'Web Wide World'], d: 'easy' },
  { q: 'What is the freezing point of water in Fahrenheit?', a: '32 °F', pool: ['0 °F', '100 °F', '212 °F'], d: 'medium' },
  { q: 'What is the boiling point of water in Fahrenheit?', a: '212 °F', pool: ['100 °F', '180 °F', '32 °F'], d: 'medium' },
  { q: 'Which hand is a watch traditionally worn on?', a: 'The non-dominant hand', pool: ['Always the right', 'Always the left', 'Either shoulder'], d: 'medium' },
  { q: 'What does a thermostat control?', a: 'Temperature', pool: ['Humidity', 'Air pressure', 'Light level'], d: 'easy' },
  { q: 'What is a "blueprint" used for?', a: 'Showing a technical plan', pool: ['Colouring walls', 'Printing photos', 'Storing files'], d: 'medium' },
  { q: 'What does "RSVP" ask you to do?', a: 'Reply to an invitation', pool: ['Arrive early', 'Bring a gift', 'Dress formally'], d: 'medium' },
  { q: 'What does "etc." stand for?', a: 'Et cetera', pool: ['Estimated total cost', 'Extra to consider', 'Ending the case'], d: 'medium' },
  { q: 'What does "e.g." mean?', a: 'For example', pool: ['That is', 'And so on', 'Note well'], d: 'medium' },
  { q: 'What does "i.e." mean?', a: 'That is', pool: ['For example', 'And others', 'In effect'], d: 'medium' },
  { q: 'What does "vs." stand for?', a: 'Versus', pool: ['Various', 'Very short', 'Visual set'], d: 'easy' },
  { q: 'What does "ASAP" stand for?', a: 'As soon as possible', pool: ['All set and prepared', 'At some agreed point', 'After start and pause'], d: 'easy' },
  { q: 'What does "FAQ" stand for?', a: 'Frequently asked questions', pool: ['Fast answer queue', 'Formal answer quota', 'Full account query'], d: 'easy' },
  { q: 'What does "DIY" stand for?', a: 'Do it yourself', pool: ['Done in a year', 'Draw it yourself', 'Design it yourself'], d: 'easy' },
  { q: 'What does "VIP" stand for?', a: 'Very important person', pool: ['Verified identity pass', 'Visitor in place', 'Value in progress'], d: 'easy' },
  { q: 'What does "CV" stand for?', a: 'Curriculum vitae', pool: ['Career value', 'Certified verification', 'Current version'], d: 'medium' },
  { q: 'What does "PIN" stand for in banking?', a: 'Personal identification number', pool: ['Private internet number', 'Payment index number', 'Personal internet name'], d: 'medium' },
  { q: 'What does "ATM" stand for?', a: 'Automated teller machine', pool: ['Automatic transfer machine', 'Account transaction module', 'Any time money'], d: 'medium' },
  { q: 'What does "PDF" stand for?', a: 'Portable document format', pool: ['Printed document file', 'Public data file', 'Personal draft format'], d: 'medium' },
  { q: 'What is the emergency number used across the European Union?', a: '112', pool: ['999', '911', '000'], d: 'hard' },
  { q: 'What side of the road do people drive on in Japan?', a: 'The left', pool: ['The right', 'Either side', 'The centre'], d: 'hard' },
  { q: 'What side of the road do people drive on in the USA?', a: 'The right', pool: ['The left', 'Either side', 'The centre'], d: 'easy' },
  { q: 'What does a life jacket do?', a: 'Keeps you afloat', pool: ['Keeps you warm only', 'Helps you swim faster', 'Protects from impact'], d: 'easy' },
  { q: 'What is a smoke alarm designed to detect?', a: 'Smoke', pool: ['Heat only', 'Gas leaks', 'Movement'], d: 'easy' },
  { q: 'What does a seatbelt do in a crash?', a: 'Restrains the occupant', pool: ['Cushions the impact', 'Slows the car', 'Opens the airbag'], d: 'easy' },
  { q: 'What does recycling do with materials?', a: 'Reprocesses them for reuse', pool: ['Buries them safely', 'Burns them for heat', 'Stores them long term'], d: 'easy' },
  { q: 'What does a "carbon footprint" measure?', a: 'Greenhouse gases attributable to an activity', pool: ['Physical shoe size', 'Amount of coal used', 'Distance travelled'], d: 'medium' },
  { q: 'What is renewable energy?', a: 'Energy from sources that replenish naturally', pool: ['Energy that is free', 'Energy stored in batteries', 'Energy from coal'], d: 'medium' },
  { q: 'Which of these is a renewable energy source?', a: 'Wind', pool: ['Coal', 'Oil', 'Natural gas'], d: 'easy' },
  { q: 'Which of these is a fossil fuel?', a: 'Coal', pool: ['Wind', 'Solar', 'Hydro'], d: 'easy' },
  { q: 'What does a "recycling symbol" of three arrows represent?', a: 'A continuous loop of reuse', pool: ['Three waste types', 'Three collection days', 'Three factories'], d: 'medium' },
  { q: 'What does the "greenhouse effect" do to Earth?', a: 'Traps heat in the atmosphere', pool: ['Reflects all sunlight', 'Cools the surface', 'Blocks radio waves'], d: 'medium' },
  { q: 'What is biodiversity?', a: 'The variety of life in an area', pool: ['The number of trees', 'The total population', 'The size of a habitat'], d: 'medium' },
  { q: 'What is a census?', a: 'An official count of a population', pool: ['A tax return', 'An election', 'A survey of prices'], d: 'medium' },
  { q: 'What is inflation?', a: 'A general rise in prices over time', pool: ['A rise in wages only', 'A fall in prices', 'A rise in taxes'], d: 'medium' },
  { q: 'What is a budget?', a: 'A plan for income and spending', pool: ['A type of loan', 'A savings account', 'A tax bill'], d: 'easy' },
  { q: 'What is interest on a savings account?', a: 'Money the bank pays you for holding funds', pool: ['A fee you pay', 'A tax on savings', 'A transfer charge'], d: 'medium' },
  { q: 'What does a "deposit" mean at a bank?', a: 'Putting money in', pool: ['Taking money out', 'Closing an account', 'Transferring abroad'], d: 'easy' },
  { q: 'What does a "withdrawal" mean at a bank?', a: 'Taking money out', pool: ['Putting money in', 'Opening an account', 'Paying a bill'], d: 'easy' },
  { q: 'What is a mortgage?', a: 'A loan secured against property', pool: ['A savings plan', 'An insurance policy', 'A tax rebate'], d: 'medium' },
  { q: 'What does insurance provide?', a: 'Financial protection against a loss', pool: ['Guaranteed profit', 'Free repairs always', 'A savings return'], d: 'medium' },
  { q: 'What is a "receipt"?', a: 'Proof of payment', pool: ['A request for payment', 'A bank statement', 'A price list'], d: 'easy' },
  { q: 'What is an "invoice"?', a: 'A request for payment', pool: ['Proof of payment', 'A refund notice', 'A delivery note'], d: 'medium' },
  { q: 'What is a "refund"?', a: 'Money returned to a buyer', pool: ['A discount before purchase', 'A late fee', 'An extra charge'], d: 'easy' },
  { q: 'What is VAT?', a: 'A tax added to goods and services', pool: ['A type of insurance', 'A bank fee', 'A delivery charge'], d: 'medium' },
  { q: 'What is a "guarantee" on a product?', a: 'A promise to repair or replace faults', pool: ['A discount voucher', 'A delivery date', 'A price match'], d: 'easy' },
  { q: 'What is the purpose of a queue?', a: 'Serving people in order of arrival', pool: ['Grouping people by age', 'Random selection', 'Serving the fastest first'], d: 'easy' },
  { q: 'What does "recycle, reduce, reuse" encourage?', a: 'Producing less waste', pool: ['Buying more products', 'Using more energy', 'Storing more goods'], d: 'easy' },
  { q: 'What does a "will" set out?', a: 'How someone’s estate is distributed', pool: ['A yearly budget', 'A business plan', 'A rental agreement'], d: 'hard' },
  { q: 'What is a "referendum"?', a: 'A direct public vote on a question', pool: ['A parliamentary debate', 'A court ruling', 'A census'], d: 'hard' },
  { q: 'What is a "constitution"?', a: 'The fundamental rules of a state', pool: ['A tax code', 'A trade treaty', 'A criminal record'], d: 'hard' },
  { q: 'What is "jury duty"?', a: 'Serving on a jury in a trial', pool: ['Working as a judge', 'Reporting a crime', 'Guarding a court'], d: 'hard' },
  { q: 'What does "innocent until proven guilty" describe?', a: 'The presumption of innocence', pool: ['The right to silence', 'The right to appeal', 'Double jeopardy'], d: 'hard' },
  { q: 'What is a "veto"?', a: 'The power to block a decision', pool: ['The power to propose a law', 'A type of vote count', 'A public consultation'], d: 'hard' },
  { q: 'What is a "quorum"?', a: 'The minimum attendance for valid business', pool: ['A majority vote', 'A committee chair', 'An agenda item'], d: 'hard' },
  { q: 'What does "unanimous" mean?', a: 'Agreed by everyone', pool: ['Agreed by a majority', 'Agreed by no one', 'Decided by the chair'], d: 'medium' },
  { q: 'What is a "majority"?', a: 'More than half', pool: ['Exactly half', 'Less than half', 'All of them'], d: 'easy' },
  { q: 'What is a "deadline"?', a: 'The latest time something is due', pool: ['The earliest start time', 'A meeting time', 'A delivery route'], d: 'easy' },
  { q: 'What is an "agenda" for a meeting?', a: 'A list of items to discuss', pool: ['A record of decisions', 'A list of attendees', 'A room booking'], d: 'medium' },
  { q: 'What are "minutes" of a meeting?', a: 'A written record of what happened', pool: ['The length of the meeting', 'The list of topics', 'The invitation'], d: 'medium' },
  { q: 'What does "confidential" mean?', a: 'Not to be shared', pool: ['Widely published', 'Officially approved', 'Free of charge'], d: 'easy' },
  { q: 'What is a "deadline extension"?', a: 'More time to complete something', pool: ['A cancelled task', 'An earlier due date', 'A reduced workload'], d: 'easy' },
  { q: 'What does "punctual" mean?', a: 'On time', pool: ['Late', 'Early only', 'Absent'], d: 'easy' },
  { q: 'What does "verbal" communication mean?', a: 'Using spoken words', pool: ['Using written words', 'Using gestures only', 'Using images'], d: 'easy' },
  { q: 'What is "body language"?', a: 'Communication through posture and gesture', pool: ['A spoken dialect', 'A written code', 'A sign alphabet'], d: 'easy' },
  { q: 'What is "sign language" used for?', a: 'Communicating with hand shapes and gestures', pool: ['Writing shorthand', 'Reading by touch', 'Signalling at sea'], d: 'easy' },
  { q: 'What is an "interpreter"?', a: 'Someone who translates speech in real time', pool: ['Someone who writes books', 'Someone who edits film', 'Someone who reads maps'], d: 'medium' },
  { q: 'What is a "volunteer"?', a: 'Someone who works without pay', pool: ['A paid contractor', 'A part-time employee', 'A shareholder'], d: 'easy' },
  { q: 'What is a "charity"?', a: 'An organisation for public benefit', pool: ['A private business', 'A government office', 'A trade union'], d: 'easy' },
  { q: 'What is "first aid"?', a: 'Immediate help given to an injured person', pool: ['Hospital surgery', 'A health insurance plan', 'A vaccination'], d: 'easy' },
  { q: 'What does CPR stand for?', a: 'Cardiopulmonary resuscitation', pool: ['Cardiac pressure relief', 'Complete patient recovery', 'Chest and pulse response'], d: 'hard' },
  { q: 'What is the recovery position used for?', a: 'Keeping an unconscious person’s airway clear', pool: ['Stopping bleeding', 'Treating burns', 'Setting a broken bone'], d: 'hard' },
  { q: 'What should you do first in an emergency?', a: 'Check the scene is safe', pool: ['Move the casualty', 'Give water', 'Take a photo'], d: 'medium' },
  { q: 'What is a "hazard"?', a: 'Something that could cause harm', pool: ['A safety device', 'A warning light', 'An emergency exit'], d: 'easy' },
  { q: 'What is a fire extinguisher used for?', a: 'Putting out small fires', pool: ['Detecting smoke', 'Sounding an alarm', 'Cooling a room'], d: 'easy' },
  { q: 'What should you not use on an electrical fire?', a: 'Water', pool: ['A fire blanket', 'A CO₂ extinguisher', 'Dry powder'], d: 'hard' },
  { q: 'What is the purpose of a fire drill?', a: 'Practising safe evacuation', pool: ['Testing the sprinklers', 'Checking the alarm volume', 'Training firefighters'], d: 'easy' },
  { q: 'What does a "high-visibility" jacket do?', a: 'Makes the wearer easier to see', pool: ['Keeps the wearer warm', 'Protects from impact', 'Repels water only'], d: 'easy' },
  { q: 'What is a "helmet" designed to protect?', a: 'The head', pool: ['The hands', 'The feet', 'The eyes only'], d: 'easy' },
  { q: 'Why do bicycles have reflectors?', a: 'To be seen in low light', pool: ['To reduce weight', 'To improve braking', 'To measure speed'], d: 'easy' },
  { q: 'What does a "zebra crossing" mark?', a: 'A pedestrian crossing point', pool: ['A parking zone', 'A bus lane', 'A speed limit change'], d: 'easy' },
  { q: 'What does a speed limit sign show?', a: 'The maximum legal speed', pool: ['The minimum speed', 'The recommended gear', 'The distance to a town'], d: 'easy' },
  { q: 'What is a "roundabout" for?', a: 'Managing traffic at a junction', pool: ['Parking cars', 'Stopping traffic entirely', 'Measuring speed'], d: 'easy' },
  { q: 'What does a "one way" sign mean?', a: 'Traffic flows in a single direction', pool: ['No entry at all', 'Two-way traffic ahead', 'A dead end'], d: 'easy' },
  { q: 'What does a "cul-de-sac" mean?', a: 'A dead-end street', pool: ['A main road', 'A roundabout', 'A crossroads'], d: 'medium' },
  { q: 'What does "pedestrian" mean?', a: 'A person travelling on foot', pool: ['A cyclist', 'A driver', 'A passenger'], d: 'easy' },

  // Harder general knowledge — the hard tier is the thinnest, so these carry it.
  { q: 'What does the acronym "LASER" stand for?', a: 'Light amplification by stimulated emission of radiation', pool: ['Light and sound energy reflection', 'Linear amplified signal emission ray', 'Long arc semiconductor energy relay'], d: 'hard' },
  { q: 'What does "RADAR" stand for?', a: 'Radio detection and ranging', pool: ['Rapid detection and response', 'Radio directional array', 'Range and direction analysis'], d: 'hard' },
  { q: 'What does "SCUBA" stand for?', a: 'Self-contained underwater breathing apparatus', pool: ['Submerged current underwater breathing aid', 'Sealed cylinder underwater buoyancy apparatus', 'Standard compressed underwater breathing air'], d: 'hard' },
  { q: 'What is the study of handwriting called?', a: 'Graphology', pool: ['Calligraphy', 'Typography', 'Orthography'], d: 'hard' },
  { q: 'What is the study of insects called?', a: 'Entomology', pool: ['Etymology', 'Ornithology', 'Herpetology'], d: 'hard' },
  { q: 'What is the study of birds called?', a: 'Ornithology', pool: ['Entomology', 'Ichthyology', 'Mammalogy'], d: 'hard' },
  { q: 'What is the study of earthquakes called?', a: 'Seismology', pool: ['Volcanology', 'Meteorology', 'Geology'], d: 'hard' },
  { q: 'What is the study of weather called?', a: 'Meteorology', pool: ['Climatology only', 'Astronomy', 'Geology'], d: 'medium' },
  { q: 'What is the fear of confined spaces called?', a: 'Claustrophobia', pool: ['Agoraphobia', 'Acrophobia', 'Arachnophobia'], d: 'hard' },
  { q: 'What is the fear of heights called?', a: 'Acrophobia', pool: ['Claustrophobia', 'Agoraphobia', 'Hydrophobia'], d: 'hard' },
  { q: 'What is the fear of open spaces called?', a: 'Agoraphobia', pool: ['Claustrophobia', 'Acrophobia', 'Nyctophobia'], d: 'hard' },
  { q: 'What is a group of lions called?', a: 'A pride', pool: ['A pack', 'A herd', 'A flock'], d: 'medium' },
  { q: 'What is a person who cannot speak called?', a: 'Mute', pool: ['Deaf', 'Blind', 'Illiterate'], d: 'medium' },
  { q: 'What is a five-year period called?', a: 'A lustrum', pool: ['A decade', 'A quinquennial century', 'A semester'], d: 'hard' },
  { q: 'What does "per annum" mean?', a: 'Per year', pool: ['Per month', 'Per person', 'Per item'], d: 'medium' },
  { q: 'What does "per capita" mean?', a: 'Per person', pool: ['Per year', 'Per household', 'Per region'], d: 'hard' },
  { q: 'What does "status quo" mean?', a: 'The existing state of affairs', pool: ['A formal complaint', 'A future plan', 'A legal ruling'], d: 'hard' },
  { q: 'What does "bona fide" mean?', a: 'In good faith, genuine', pool: ['In bad faith', 'Under review', 'By agreement'], d: 'hard' },
  { q: 'What does "carte blanche" mean?', a: 'Complete freedom to act', pool: ['A blank contract', 'A refusal', 'A written warning'], d: 'hard' },
  { q: 'What does "de facto" mean?', a: 'In practice, whether or not by law', pool: ['By law only', 'In theory only', 'After the fact'], d: 'hard' },
  { q: 'What does "ad hoc" mean?', a: 'Formed for a specific purpose', pool: ['Permanent and formal', 'Repeated regularly', 'Agreed in advance'], d: 'hard' },
  { q: 'What does "pro rata" mean?', a: 'In proportion', pool: ['In full', 'In advance', 'In arrears'], d: 'hard' },
  { q: 'What does "quid pro quo" mean?', a: 'Something given in return for something else', pool: ['Without payment', 'Against the rules', 'Beyond doubt'], d: 'hard' },
  { q: 'What does "vice versa" mean?', a: 'The other way round', pool: ['At the same time', 'In addition', 'By contrast'], d: 'medium' },
  { q: 'What does "et al." mean in a citation?', a: 'And others', pool: ['And so on', 'For example', 'That is'], d: 'hard' },
  { q: 'What does "N.B." mean?', a: 'Note well', pool: ['Not binding', 'New batch', 'Next below'], d: 'hard' },
  { q: 'What does "circa" mean before a date?', a: 'Approximately', pool: ['Exactly', 'Before', 'After'], d: 'medium' },
  { q: 'What does "verbatim" mean?', a: 'Word for word', pool: ['In summary', 'Out loud', 'In writing'], d: 'medium' },
  { q: 'What does "unilateral" mean?', a: 'Done by one side alone', pool: ['Done by both sides', 'Done by many parties', 'Done in secret'], d: 'hard' },
  { q: 'What does "ambiguous" mean?', a: 'Open to more than one meaning', pool: ['Clearly defined', 'Deliberately false', 'Very detailed'], d: 'medium' },
];
