/** Final top-up. Sized ~1.5x the residual so dedupe collisions still leave a full bank. */
type F = { q: string; a: string; pool: string[]; d: 'easy' | 'medium' | 'hard' };

export const GEO3: F[] = [
  { q: 'What is a very large body of salt water called?', a: 'An ocean', pool: ['A lake', 'A river', 'A bay'], d: 'easy' },
  { q: 'What is a smaller flow of water into a river called?', a: 'A tributary', pool: ['A delta', 'An estuary', 'A basin'], d: 'easy' },
  { q: 'What is the top of a mountain called?', a: 'The summit', pool: ['The base', 'The ridge', 'The slope'], d: 'easy' },
  { q: 'What kind of weather does a rainforest have?', a: 'Warm and wet', pool: ['Cold and dry', 'Hot and dry', 'Cool and windy'], d: 'easy' },
  { q: 'What is a large sheet of moving ice called?', a: 'A glacier', pool: ['An iceberg', 'A snowfield', 'A floe'], d: 'easy' },
  { q: 'What is a mountain that erupts called?', a: 'A volcano', pool: ['A geyser', 'A crater', 'A fault'], d: 'easy' },
  { q: 'What do we call shaking of the ground?', a: 'An earthquake', pool: ['A landslide', 'An avalanche', 'A tsunami'], d: 'easy' },
  { q: 'What is a giant ocean wave caused by an earthquake?', a: 'A tsunami', pool: ['A tide', 'A current', 'A swell'], d: 'easy' },
  { q: 'What is a spinning storm over warm ocean water called?', a: 'A hurricane', pool: ['A tornado', 'A blizzard', 'A monsoon'], d: 'easy' },
  { q: 'What is a spinning column of air over land called?', a: 'A tornado', pool: ['A hurricane', 'A typhoon', 'A cyclone'], d: 'easy' },
  { q: 'What is a seasonal wind bringing heavy rain called?', a: 'A monsoon', pool: ['A trade wind', 'A jet stream', 'A gale'], d: 'easy' },
  { q: 'What instrument measures air pressure?', a: 'A barometer', pool: ['A thermometer', 'A hygrometer', 'An anemometer'], d: 'easy' },
  { q: 'What instrument measures wind speed?', a: 'An anemometer', pool: ['A barometer', 'A thermometer', 'A seismograph'], d: 'easy' },
  { q: 'What instrument measures earthquakes?', a: 'A seismograph', pool: ['A barometer', 'An anemometer', 'A hygrometer'], d: 'easy' },
  { q: 'What is grassland with scattered trees in Africa called?', a: 'Savanna', pool: ['Tundra', 'Taiga', 'Steppe'], d: 'easy' },
  { q: 'What is the cold treeless region near the poles called?', a: 'Tundra', pool: ['Savanna', 'Prairie', 'Chaparral'], d: 'easy' },
  { q: 'What is permanently frozen ground called?', a: 'Permafrost', pool: ['Glacier', 'Tundra', 'Ice cap'], d: 'medium' },
  { q: 'What is a raised flat area of land called?', a: 'A plateau', pool: ['A valley', 'A basin', 'A gorge'], d: 'medium' },
];

export const CHEM3: F[] = [
  { q: 'What is the chemical symbol for oxygen?', a: 'O', pool: ['Ox', 'Og', 'Om'], d: 'easy' },
  { q: 'What is the chemical symbol for carbon?', a: 'C', pool: ['Ca', 'Cr', 'Co'], d: 'easy' },
  { q: 'What is the chemical symbol for iron?', a: 'Fe', pool: ['Ir', 'In', 'I'], d: 'easy' },
  { q: 'What is the chemical symbol for silver?', a: 'Ag', pool: ['Si', 'Sv', 'Au'], d: 'easy' },
  { q: 'What is the chemical symbol for sodium?', a: 'Na', pool: ['So', 'Sd', 'S'], d: 'easy' },
  { q: 'What is the chemical symbol for potassium?', a: 'K', pool: ['P', 'Po', 'Pt'], d: 'easy' },
  { q: 'What is the chemical symbol for nitrogen?', a: 'N', pool: ['Ni', 'Na', 'Ne'], d: 'easy' },
  { q: 'What is the chemical symbol for helium?', a: 'He', pool: ['H', 'Hl', 'Hm'], d: 'easy' },
  { q: 'What is the chemical symbol for copper?', a: 'Cu', pool: ['Co', 'Cp', 'C'], d: 'easy' },
  { q: 'What is the chemical symbol for lead?', a: 'Pb', pool: ['Le', 'Ld', 'L'], d: 'easy' },
  { q: 'What is the chemical formula for carbon dioxide?', a: 'CO₂', pool: ['CO', 'C₂O', 'CaO'], d: 'easy' },
  { q: 'What is the chemical formula for methane?', a: 'CH₄', pool: ['C₂H₆', 'CH₃', 'CH₂'], d: 'easy' },
  { q: 'Which gas is used to fill party balloons that float?', a: 'Helium', pool: ['Hydrogen', 'Oxygen', 'Neon'], d: 'easy' },
  { q: 'Which gas makes fizzy drinks bubbly?', a: 'Carbon dioxide', pool: ['Oxygen', 'Nitrogen', 'Helium'], d: 'easy' },
  { q: 'What is the process of a gas becoming a liquid?', a: 'Condensation', pool: ['Evaporation', 'Sublimation', 'Melting'], d: 'easy' },
  { q: 'What is the process of a solid becoming a liquid?', a: 'Melting', pool: ['Freezing', 'Boiling', 'Condensing'], d: 'easy' },
  { q: 'Which substance is a good solvent for many things?', a: 'Water', pool: ['Oil', 'Sand', 'Wax'], d: 'easy' },
  { q: 'What do we call a substance that cannot be broken down chemically?', a: 'An element', pool: ['A compound', 'A mixture', 'A solution'], d: 'easy' },
  { q: 'What does a pH below 7 indicate?', a: 'An acid', pool: ['A base', 'A neutral solution', 'A salt'], d: 'easy' },
  { q: 'What does a pH above 7 indicate?', a: 'A base', pool: ['An acid', 'A neutral solution', 'Pure water'], d: 'easy' },
  { q: 'What is filtration used to separate?', a: 'Solids from liquids', pool: ['Two liquids', 'Two gases', 'Colours from ink'], d: 'medium' },
  { q: 'What is chromatography used to separate?', a: 'Mixtures of dissolved substances', pool: ['Solids from liquids', 'Gases from liquids', 'Metals from ores'], d: 'medium' },
  { q: 'What is evaporation used to recover?', a: 'A dissolved solid from solution', pool: ['A gas from air', 'A liquid from a solid', 'Two mixed liquids'], d: 'medium' },
  { q: 'What is a saturated solution?', a: 'One that can dissolve no more solute', pool: ['One with no solute', 'One that is boiling', 'One that has separated'], d: 'medium' },
  { q: 'What does a combustion reaction need?', a: 'Fuel, oxygen and heat', pool: ['Fuel and water', 'Oxygen and nitrogen', 'Heat and pressure only'], d: 'medium' },
  { q: 'What is the conservation of mass in a reaction?', a: 'Mass of reactants equals mass of products', pool: ['Mass always increases', 'Mass always decreases', 'Mass depends on temperature'], d: 'medium' },
];

export const PHYS3: F[] = [
  { q: 'Which of these is a source of light?', a: 'The Sun', pool: ['The Moon', 'A mirror', 'A window'], d: 'easy' },
  { q: 'Why does the Moon appear to shine?', a: 'It reflects sunlight', pool: ['It burns like a star', 'It glows from heat', 'It emits its own light'], d: 'easy' },
  { q: 'How many planets are in the Solar System?', a: 'Eight', pool: ['Seven', 'Nine', 'Ten'], d: 'easy' },
  { q: 'What is at the centre of the Solar System?', a: 'The Sun', pool: ['The Earth', 'The Moon', 'Jupiter'], d: 'easy' },
  { q: 'What is the largest planet in the Solar System?', a: 'Jupiter', pool: ['Saturn', 'Neptune', 'Earth'], d: 'easy' },
  { q: 'What orbits the Earth?', a: 'The Moon', pool: ['The Sun', 'Mars', 'Venus'], d: 'easy' },
  { q: 'What is a star made mostly of?', a: 'Hydrogen', pool: ['Rock', 'Iron', 'Water'], d: 'easy' },
  { q: 'How long does Earth take to orbit the Sun?', a: 'About a year', pool: ['About a day', 'About a month', 'About ten years'], d: 'easy' },
  { q: 'How long does Earth take to spin once?', a: 'About a day', pool: ['About an hour', 'About a month', 'About a year'], d: 'easy' },
  { q: 'What happens in a solar eclipse?', a: 'The Moon blocks the Sun', pool: ['Earth blocks the Sun', 'The Sun blocks the Moon', 'Earth blocks the Moon'], d: 'easy' },
  { q: 'What happens in a lunar eclipse?', a: 'Earth’s shadow falls on the Moon', pool: ['The Moon blocks the Sun', 'The Moon stops orbiting', 'The Sun dims'], d: 'medium' },
  { q: 'What is a light year a measure of?', a: 'Distance', pool: ['Time', 'Brightness', 'Speed'], d: 'medium' },
  { q: 'What holds planets in orbit around the Sun?', a: 'Gravity', pool: ['Magnetism', 'Air pressure', 'Solar wind'], d: 'easy' },
  { q: 'Which is bigger, the Sun or the Earth?', a: 'The Sun', pool: ['The Earth', 'They are the same', 'It varies'], d: 'easy' },
  { q: 'What does a lever help you do?', a: 'Lift a load with less force', pool: ['Move faster', 'Reduce weight', 'Create energy'], d: 'easy' },
  { q: 'What does a pulley help you do?', a: 'Change the direction of a force', pool: ['Create energy', 'Reduce mass', 'Increase gravity'], d: 'easy' },
  { q: 'What is a closed path that electricity flows around?', a: 'A circuit', pool: ['A conductor', 'A resistor', 'A capacitor'], d: 'easy' },
  { q: 'What happens if a circuit is broken?', a: 'Current stops flowing', pool: ['Current increases', 'Voltage doubles', 'Resistance drops'], d: 'easy' },
  { q: 'What does a switch do in a circuit?', a: 'Opens or closes the path', pool: ['Stores charge', 'Increases voltage', 'Measures current'], d: 'easy' },
  { q: 'What does a fuse protect against?', a: 'Excessive current', pool: ['Low voltage', 'Static charge', 'Overheating motors only'], d: 'medium' },
  { q: 'What poles of two magnets attract?', a: 'Opposite poles', pool: ['Like poles', 'Any poles', 'Neither'], d: 'easy' },
  { q: 'What material is attracted to a magnet?', a: 'Iron', pool: ['Copper', 'Aluminium', 'Plastic'], d: 'easy' },
  { q: 'What is static electricity?', a: 'A build-up of charge on a surface', pool: ['A steady current', 'A magnetic field', 'A voltage drop'], d: 'medium' },
  { q: 'What is the unit of temperature in the SI system?', a: 'The kelvin', pool: ['The Celsius degree', 'The Fahrenheit degree', 'The joule'], d: 'medium' },
  { q: 'What is the SI unit of mass?', a: 'The kilogram', pool: ['The newton', 'The gram', 'The pound'], d: 'medium' },
  { q: 'What is the SI unit of time?', a: 'The second', pool: ['The minute', 'The hour', 'The hertz'], d: 'medium' },
  { q: 'What is the SI unit of length?', a: 'The metre', pool: ['The centimetre', 'The foot', 'The mile'], d: 'medium' },
  { q: 'What is thermal conduction?', a: 'Heat moving through a solid by contact', pool: ['Heat moving by fluid flow', 'Heat moving as waves', 'Heat being stored'], d: 'medium' },
  { q: 'How does heat reach Earth from the Sun?', a: 'By radiation', pool: ['By conduction', 'By convection', 'By the solar wind'], d: 'medium' },
  { q: 'Which colour absorbs the most heat?', a: 'Black', pool: ['White', 'Silver', 'Yellow'], d: 'medium' },
];

export const HIST3: F[] = [
  { q: 'Which country built the Great Wall?', a: 'China', pool: ['Japan', 'Mongolia', 'Korea'], d: 'easy' },
  { q: 'In which country is the Great Pyramid of Giza?', a: 'Egypt', pool: ['Sudan', 'Iraq', 'Mexico'], d: 'easy' },
  { q: 'Which city was the heart of the Roman Empire?', a: 'Rome', pool: ['Athens', 'Cairo', 'Istanbul'], d: 'easy' },
  { q: 'What is a period of a hundred years called?', a: 'A century', pool: ['A decade', 'A millennium', 'An era'], d: 'easy' },
  { q: 'What is a period of a thousand years called?', a: 'A millennium', pool: ['A century', 'A decade', 'An age'], d: 'easy' },
  { q: 'What is a period of ten years called?', a: 'A decade', pool: ['A century', 'A score', 'A generation'], d: 'easy' },
  { q: 'What does AD stand for in dates?', a: 'Anno Domini', pool: ['After Death', 'Ancient Days', 'Alternate Date'], d: 'easy' },
  { q: 'Which invention allowed books to be mass-produced?', a: 'The printing press', pool: ['The typewriter', 'The camera', 'The telegraph'], d: 'easy' },
  { q: 'Which machine transformed travel in the 19th century?', a: 'The steam locomotive', pool: ['The aeroplane', 'The motorcar', 'The bicycle'], d: 'easy' },
  { q: 'Who invented the telephone, by common attribution?', a: 'Alexander Graham Bell', pool: ['Thomas Edison', 'Nikola Tesla', 'Guglielmo Marconi'], d: 'easy' },
  { q: 'Who is credited with the practical light bulb?', a: 'Thomas Edison', pool: ['Alexander Graham Bell', 'Michael Faraday', 'James Watt'], d: 'easy' },
  { q: 'Who were the first to fly a powered aeroplane?', a: 'The Wright brothers', pool: ['The Montgolfier brothers', 'Charles Lindbergh', 'Amelia Earhart'], d: 'easy' },
  { q: 'Which continent were the ancient Maya from?', a: 'North America', pool: ['South America', 'Africa', 'Asia'], d: 'easy' },
  { q: 'Which ancient people gave us the Olympic Games?', a: 'The Greeks', pool: ['The Romans', 'The Egyptians', 'The Persians'], d: 'easy' },
  { q: 'What did knights wear for protection?', a: 'Armour', pool: ['Robes', 'Togas', 'Furs'], d: 'easy' },
  { q: 'What were the large sailing ships of exploration called?', a: 'Galleons', pool: ['Canoes', 'Steamers', 'Barges'], d: 'easy' },
  { q: 'Which two cities were destroyed by atomic bombs in 1945?', a: 'Hiroshima and Nagasaki', pool: ['Tokyo and Osaka', 'Kyoto and Kobe', 'Nagoya and Sapporo'], d: 'medium' },
  { q: 'Which country was divided into East and West after 1945?', a: 'Germany', pool: ['France', 'Poland', 'Austria'], d: 'medium' },
  { q: 'What was the Renaissance a rebirth of?', a: 'Classical art and learning', pool: ['Religious rule', 'Feudal law', 'Military conquest'], d: 'medium' },
  { q: 'Who painted the Mona Lisa?', a: 'Leonardo da Vinci', pool: ['Michelangelo', 'Raphael', 'Botticelli'], d: 'easy' },
  { q: 'Which scientist proposed that Earth orbits the Sun?', a: 'Copernicus', pool: ['Ptolemy', 'Aristotle', 'Kepler'], d: 'medium' },
  { q: 'Which scientist was tried for supporting heliocentrism?', a: 'Galileo', pool: ['Newton', 'Copernicus', 'Brahe'], d: 'medium' },
  { q: 'What was the Magna Carta signed at?', a: 'Runnymede', pool: ['Westminster', 'Canterbury', 'York'], d: 'medium' },
  { q: 'What was the Boston Tea Party a protest against?', a: 'British taxation', pool: ['French rule', 'Slavery', 'Land seizures'], d: 'medium' },
  { q: 'Which document begins "We the People"?', a: 'The US Constitution', pool: ['The Declaration of Independence', 'The Bill of Rights', 'The Gettysburg Address'], d: 'medium' },
  { q: 'Which epidemic swept the world in 1918?', a: 'Spanish flu', pool: ['The Black Death', 'Cholera', 'Polio'], d: 'medium' },
];

export const SPORT3: F[] = [
  { q: 'What shape is a football pitch?', a: 'A rectangle', pool: ['A square', 'An oval', 'A circle'], d: 'easy' },
  { q: 'What do you kick in football?', a: 'The ball', pool: ['The goal', 'The net', 'The post'], d: 'easy' },
  { q: 'What is the aim in football?', a: 'To score more goals', pool: ['To hold the ball longest', 'To run furthest', 'To make most passes'], d: 'easy' },
  { q: 'Which sport do you run 100 metres in?', a: 'Athletics', pool: ['Swimming', 'Cycling', 'Rowing'], d: 'easy' },
  { q: 'What do athletes jump over in hurdles?', a: 'Hurdles', pool: ['Bars', 'Nets', 'Poles'], d: 'easy' },
  { q: 'Which athletics event uses a long pole to clear a bar?', a: 'Pole vault', pool: ['High jump', 'Long jump', 'Triple jump'], d: 'easy' },
  { q: 'Which athletics event involves throwing a metal ball?', a: 'Shot put', pool: ['Javelin', 'Discus', 'Hammer'], d: 'easy' },
  { q: 'Which athletics event involves throwing a spear?', a: 'Javelin', pool: ['Shot put', 'Discus', 'Hammer'], d: 'easy' },
  { q: 'Which athletics event involves throwing a disc?', a: 'Discus', pool: ['Javelin', 'Shot put', 'Hammer'], d: 'easy' },
  { q: 'What do gymnasts perform on in artistic gymnastics?', a: 'Apparatus like beams and bars', pool: ['A trampoline only', 'Ice', 'Water'], d: 'easy' },
  { q: 'Which sport is played on a court with a net at waist height?', a: 'Volleyball', pool: ['Basketball', 'Football', 'Handball'], d: 'easy' },
  { q: 'Which sport involves rolling a ball at pins?', a: 'Bowling', pool: ['Curling', 'Boules', 'Croquet'], d: 'easy' },
  { q: 'Which sport is played on horseback with a ball and mallet?', a: 'Polo', pool: ['Dressage', 'Show jumping', 'Racing'], d: 'easy' },
  { q: 'Which sport uses a sword?', a: 'Fencing', pool: ['Archery', 'Judo', 'Karate'], d: 'easy' },
  { q: 'Which sport uses a bow and arrow?', a: 'Archery', pool: ['Fencing', 'Shooting', 'Darts'], d: 'easy' },
  { q: 'Which sport takes place on a track with cars?', a: 'Motor racing', pool: ['Cycling', 'Athletics', 'Rowing'], d: 'easy' },
  { q: 'Which sport uses oars in a boat?', a: 'Rowing', pool: ['Sailing', 'Canoeing', 'Kayaking'], d: 'easy' },
  { q: 'Which sport uses a sail and wind?', a: 'Sailing', pool: ['Rowing', 'Surfing', 'Diving'], d: 'easy' },
  { q: 'Which sport is performed on a board on waves?', a: 'Surfing', pool: ['Skateboarding', 'Snowboarding', 'Sailing'], d: 'easy' },
  { q: 'Which sport is performed on a board on snow?', a: 'Snowboarding', pool: ['Surfing', 'Skiing', 'Skating'], d: 'easy' },
  { q: 'Which martial art originated in Japan and uses throws?', a: 'Judo', pool: ['Karate', 'Taekwondo', 'Kung fu'], d: 'medium' },
  { q: 'Which martial art originated in Korea?', a: 'Taekwondo', pool: ['Judo', 'Karate', 'Aikido'], d: 'medium' },
  { q: 'What does a coxswain do in rowing?', a: 'Steers and calls the rhythm', pool: ['Rows hardest', 'Times the race', 'Repairs the boat'], d: 'medium' },
  { q: 'What is a "double fault" in tennis?', a: 'Missing both serves', pool: ['Two errors in a rally', 'Hitting the net twice', 'Losing two points'], d: 'medium' },
  { q: 'What is a "tie-break" used for in tennis?', a: 'Deciding a set at 6-6', pool: ['Restarting a match', 'Replacing a set', 'Deciding a serve order'], d: 'medium' },
  { q: 'What is a "penalty shootout" for in football?', a: 'Deciding a drawn knockout match', pool: ['Punishing a red card', 'Restarting after half time', 'Awarding extra goals'], d: 'medium' },
  { q: 'What is "extra time" in football?', a: 'Additional periods after a draw', pool: ['Stoppage for injuries', 'Time added at half time', 'A substitution window'], d: 'medium' },
  { q: 'How many substitutes are typically allowed in a football match?', a: 'Five in most competitions', pool: ['One', 'Ten', 'Unlimited'], d: 'medium' },
  { q: 'What is a "no-ball" in cricket?', a: 'An illegal delivery', pool: ['A missed swing', 'A dropped catch', 'A dead ball'], d: 'hard' },
  { q: 'What is a "maiden over" in cricket?', a: 'An over with no runs scored', pool: ['A bowler’s first over', 'An over with a wicket', 'The final over'], d: 'hard' },
  { q: 'What is a "hat-trick" in cricket?', a: 'Three wickets in three balls', pool: ['Three sixes in a row', 'Three catches', 'Three overs unbeaten'], d: 'hard' },
  { q: 'What is an "albatross" in golf?', a: 'Three strokes under par', pool: ['Two under par', 'One under par', 'Four under par'], d: 'hard' },
  { q: 'What is a "hole in one" in golf?', a: 'Sinking the ball from the tee', pool: ['Finishing under par', 'Winning a hole', 'A perfect putt'], d: 'hard' },
  { q: 'What does "par" mean in golf?', a: 'The expected number of strokes', pool: ['The best possible score', 'The winning score', 'The number of holes'], d: 'hard' },
  { q: 'What is a "technical knockout" in boxing?', a: 'The referee stops the fight', pool: ['A knockout in round one', 'A win on points', 'A disqualification'], d: 'hard' },
  { q: 'How long is a professional boxing round?', a: 'Three minutes', pool: ['Two minutes', 'Five minutes', 'One minute'], d: 'hard' },
];

export const FOOD3: F[] = [
  { q: 'Which meal is eaten in the morning?', a: 'Breakfast', pool: ['Lunch', 'Dinner', 'Supper'], d: 'easy' },
  { q: 'What utensil is used to eat soup?', a: 'A spoon', pool: ['A fork', 'A knife', 'Chopsticks'], d: 'easy' },
  { q: 'What appliance keeps food cold?', a: 'A refrigerator', pool: ['An oven', 'A toaster', 'A kettle'], d: 'easy' },
  { q: 'What appliance boils water quickly?', a: 'A kettle', pool: ['A blender', 'A toaster', 'A grill'], d: 'easy' },
  { q: 'What do you use to whisk eggs?', a: 'A whisk', pool: ['A ladle', 'A peeler', 'A grater'], d: 'easy' },
  { q: 'What is used to grate cheese?', a: 'A grater', pool: ['A whisk', 'A ladle', 'A sieve'], d: 'easy' },
  { q: 'Which of these is a herb?', a: 'Basil', pool: ['Cinnamon', 'Nutmeg', 'Pepper'], d: 'easy' },
  { q: 'Which of these is a spice?', a: 'Cinnamon', pool: ['Basil', 'Parsley', 'Mint'], d: 'easy' },
  { q: 'What is the main ingredient in butter?', a: 'Cream', pool: ['Oil', 'Milk powder', 'Egg'], d: 'easy' },
  { q: 'Which food group are bread and rice in?', a: 'Carbohydrates', pool: ['Proteins', 'Fats', 'Vitamins'], d: 'easy' },
  { q: 'Which food group are meat and beans in?', a: 'Proteins', pool: ['Carbohydrates', 'Fats', 'Minerals'], d: 'easy' },
  { q: 'Which nutrient gives the most energy per gram?', a: 'Fat', pool: ['Protein', 'Carbohydrate', 'Fibre'], d: 'medium' },
  { q: 'What does fibre help with?', a: 'Digestion', pool: ['Bone growth', 'Muscle building', 'Eyesight'], d: 'medium' },
  { q: 'Which mineral is important for strong bones?', a: 'Calcium', pool: ['Iron', 'Zinc', 'Sodium'], d: 'medium' },
  { q: 'Which mineral helps carry oxygen in blood?', a: 'Iron', pool: ['Calcium', 'Potassium', 'Magnesium'], d: 'medium' },
  { q: 'Why should raw meat be kept separate from other food?', a: 'To avoid cross-contamination', pool: ['To keep it warm', 'To save space', 'To preserve colour'], d: 'medium' },
  { q: 'What is the danger zone temperature range for food?', a: 'Roughly 5 °C to 60 °C', pool: ['Below 0 °C', 'Above 100 °C', 'Roughly 0 °C to 4 °C'], d: 'medium' },
  { q: 'Why should you wash hands before cooking?', a: 'To prevent spreading bacteria', pool: ['To warm them up', 'To improve taste', 'To soften skin'], d: 'medium' },
  { q: 'What does "best before" indicate?', a: 'Quality, not safety', pool: ['Safety only', 'Sell-by date', 'Manufacture date'], d: 'medium' },
  { q: 'What does "use by" indicate?', a: 'The safety deadline', pool: ['Peak quality only', 'Stock rotation', 'Packing date'], d: 'medium' },
  { q: 'What is the purpose of sifting flour?', a: 'To remove lumps and add air', pool: ['To dry it', 'To add gluten', 'To sweeten it'], d: 'medium' },
  { q: 'What does baking powder do?', a: 'Releases gas to raise a bake', pool: ['Adds sweetness', 'Adds colour', 'Absorbs moisture'], d: 'medium' },
  { q: 'What is the difference between baking soda and baking powder?', a: 'Baking powder already contains an acid', pool: ['Baking soda is sweeter', 'Baking powder is a fat', 'They are identical'], d: 'medium' },
  { q: 'What is "folding" in baking?', a: 'Gently combining to keep air in', pool: ['Beating vigorously', 'Kneading firmly', 'Chilling the mix'], d: 'medium' },
  { q: 'What is "creaming" butter and sugar for?', a: 'To trap air for a lighter texture', pool: ['To melt the butter', 'To dissolve the sugar', 'To cool the mixture'], d: 'medium' },
  { q: 'Why is an egg wash brushed on pastry?', a: 'For a golden glossy finish', pool: ['To add sweetness', 'To stop rising', 'To add salt'], d: 'medium' },
  { q: 'What is "blind baking"?', a: 'Baking a pastry case before filling it', pool: ['Baking without a recipe', 'Baking at low heat', 'Baking uncovered'], d: 'hard' },
  { q: 'What is a "brine" made of?', a: 'Salt dissolved in water', pool: ['Sugar and vinegar', 'Oil and herbs', 'Wine and stock'], d: 'hard' },
  { q: 'What is "curing" food with salt for?', a: 'Drawing out moisture to preserve it', pool: ['Adding moisture', 'Speeding cooking', 'Softening texture'], d: 'hard' },
];

export const POP3: F[] = [
  { q: 'What is a group of musicians playing together called?', a: 'A band', pool: ['A choir', 'A cast', 'A troupe'], d: 'easy' },
  { q: 'What is the words of a song called?', a: 'The lyrics', pool: ['The melody', 'The chorus only', 'The tempo'], d: 'easy' },
  { q: 'What is the repeated part of a song called?', a: 'The chorus', pool: ['The verse', 'The bridge', 'The intro'], d: 'easy' },
  { q: 'What is the speed of a piece of music called?', a: 'The tempo', pool: ['The pitch', 'The volume', 'The key'], d: 'easy' },
  { q: 'What is how high or low a note sounds called?', a: 'Pitch', pool: ['Tempo', 'Volume', 'Timbre'], d: 'easy' },
  { q: 'Which instrument is a woodwind?', a: 'The clarinet', pool: ['The trumpet', 'The violin', 'The drum'], d: 'easy' },
  { q: 'Which instrument is a string instrument?', a: 'The cello', pool: ['The flute', 'The trombone', 'The cymbal'], d: 'easy' },
  { q: 'Which instrument is the largest of the string family?', a: 'The double bass', pool: ['The cello', 'The viola', 'The violin'], d: 'medium' },
  { q: 'What does a DJ do?', a: 'Plays and mixes recorded music', pool: ['Writes symphonies', 'Conducts orchestras', 'Tunes pianos'], d: 'easy' },
  { q: 'What is a music album?', a: 'A collection of recorded tracks', pool: ['A single song', 'A concert venue', 'A music magazine'], d: 'easy' },
  { q: 'What is a "single" in music?', a: 'One song released on its own', pool: ['A solo performer', 'An album track only', 'A live recording'], d: 'easy' },
  { q: 'What is a live music performance called?', a: 'A concert', pool: ['A rehearsal', 'A recording', 'A broadcast'], d: 'easy' },
  { q: 'What is a practice session before a performance?', a: 'A rehearsal', pool: ['A concert', 'An encore', 'A premiere'], d: 'easy' },
  { q: 'What is an extra performance after applause called?', a: 'An encore', pool: ['A prelude', 'An interlude', 'An overture'], d: 'medium' },
  { q: 'What is the first showing of a film called?', a: 'The premiere', pool: ['The trailer', 'The rerun', 'The matinee'], d: 'easy' },
  { q: 'What is a sequel?', a: 'A follow-up to an earlier story', pool: ['A story set before', 'A remake', 'A spin-off'], d: 'easy' },
  { q: 'What is a prequel?', a: 'A story set before the original', pool: ['A follow-up story', 'A remake', 'A sequel'], d: 'easy' },
  { q: 'What is an animated film made of?', a: 'A sequence of drawn or rendered frames', pool: ['Live actors only', 'Still photographs', 'Text and audio'], d: 'easy' },
  { q: 'What is a documentary about?', a: 'Real events and people', pool: ['Invented characters', 'Future predictions', 'Fantasy worlds'], d: 'easy' },
  { q: 'What is a comedy meant to do?', a: 'Make the audience laugh', pool: ['Frighten the audience', 'Teach a skill', 'Report the news'], d: 'easy' },
  { q: 'What genre involves scares and suspense?', a: 'Horror', pool: ['Comedy', 'Romance', 'Documentary'], d: 'easy' },
  { q: 'What genre is set in imagined future technology?', a: 'Science fiction', pool: ['Historical drama', 'Western', 'Biography'], d: 'easy' },
  { q: 'What genre involves magic and imagined worlds?', a: 'Fantasy', pool: ['Realism', 'Documentary', 'Satire'], d: 'easy' },
  { q: 'What is the person who writes a play called?', a: 'A playwright', pool: ['A novelist', 'A poet', 'A librettist'], d: 'medium' },
  { q: 'What is the person who writes an opera’s words called?', a: 'A librettist', pool: ['A playwright', 'A composer', 'A conductor'], d: 'medium' },
  { q: 'What is the person who writes music called?', a: 'A composer', pool: ['A conductor', 'A performer', 'A producer'], d: 'medium' },
  { q: 'What is the audience area of a theatre called?', a: 'The auditorium', pool: ['The stage', 'The wings', 'The green room'], d: 'medium' },
  { q: 'What are the sides of a stage hidden from view called?', a: 'The wings', pool: ['The stalls', 'The gallery', 'The pit'], d: 'medium' },
  { q: 'What is a stage whisper directed at the audience called?', a: 'An aside', pool: ['A soliloquy', 'A monologue', 'A prologue'], d: 'medium' },
  { q: 'What is a long speech by one character to others called?', a: 'A monologue', pool: ['A dialogue', 'An aside', 'A chorus'], d: 'medium' },
  { q: 'What is the opening section of a play called?', a: 'The prologue', pool: ['The epilogue', 'The interval', 'The finale'], d: 'medium' },
  { q: 'What is the closing section of a play called?', a: 'The epilogue', pool: ['The prologue', 'The overture', 'The prelude'], d: 'medium' },
  { q: 'What is the orchestral opening of an opera called?', a: 'The overture', pool: ['The finale', 'The aria', 'The recitative'], d: 'medium' },
  { q: 'What is a solo song in an opera called?', a: 'An aria', pool: ['A chorus', 'An overture', 'A duet'], d: 'medium' },
];
