/** Shortfall-closing rows, part three: technology, food, pop culture, biology. */
type F = { q: string; a: string; pool: string[]; d: 'easy' | 'medium' | 'hard' };

export const TECH_FACTS2: F[] = [
  { q: 'What does a keyboard let you do?', a: 'Enter text', pool: ['Display images', 'Store files', 'Print pages'], d: 'easy' },
  { q: 'What is the brain of a computer called?', a: 'The CPU', pool: ['The RAM', 'The GPU', 'The SSD'], d: 'easy' },
  { q: 'What does RAM hold?', a: 'Data in active use', pool: ['Data permanently', 'The operating system only', 'Printed documents'], d: 'easy' },
  { q: 'What does a printer produce?', a: 'Paper copies', pool: ['Digital files', 'Sound', 'Video'], d: 'easy' },
  { q: 'What is an email address usually separated by?', a: 'An @ symbol', pool: ['A hash', 'A slash', 'A colon'], d: 'easy' },
  { q: 'What is a common shortcut to copy?', a: 'Ctrl+C', pool: ['Ctrl+V', 'Ctrl+Z', 'Ctrl+S'], d: 'easy' },
  { q: 'What is a common shortcut to undo?', a: 'Ctrl+Z', pool: ['Ctrl+Y', 'Ctrl+U', 'Ctrl+D'], d: 'easy' },
  { q: 'What is a common shortcut to save?', a: 'Ctrl+S', pool: ['Ctrl+A', 'Ctrl+F', 'Ctrl+W'], d: 'easy' },
  { q: 'What is the small picture representing a program called?', a: 'An icon', pool: ['A widget', 'A cursor', 'A pixel'], d: 'easy' },
  { q: 'What is the smallest element of a digital image?', a: 'A pixel', pool: ['A byte', 'A vector', 'A frame'], d: 'easy' },
  { q: 'What does "app" stand for?', a: 'Application', pool: ['Appliance', 'Applet', 'Approval'], d: 'easy' },
  { q: 'What stores files permanently in a computer?', a: 'The hard drive or SSD', pool: ['The RAM', 'The CPU cache', 'The clipboard'], d: 'easy' },
  { q: 'What is a folder used for?', a: 'Organising files', pool: ['Running programs', 'Connecting to networks', 'Encrypting data'], d: 'easy' },
  { q: 'What is spam in email?', a: 'Unwanted bulk messages', pool: ['Encrypted mail', 'Draft messages', 'Archived mail'], d: 'easy' },
  { q: 'What is a password used for?', a: 'Proving who you are', pool: ['Speeding up the computer', 'Saving files', 'Formatting drives'], d: 'easy' },
  { q: 'What does a webcam capture?', a: 'Video', pool: ['Text', 'Only still photos', 'Sound only'], d: 'easy' },
  { q: 'What does a mouse control on screen?', a: 'The pointer', pool: ['The volume', 'The brightness', 'The clock'], d: 'easy' },
  { q: 'What does "Wi-Fi" connect devices to?', a: 'A network without wires', pool: ['Mains electricity', 'A printer only', 'A monitor'], d: 'easy' },
  { q: 'What is a QR code scanned with?', a: 'A camera', pool: ['A microphone', 'A speaker', 'A keyboard'], d: 'easy' },
  { q: 'What does GPS help you do?', a: 'Find your location', pool: ['Make calls', 'Store photos', 'Charge faster'], d: 'easy' },
  { q: 'What is a firewall for?', a: 'Filtering network traffic', pool: ['Cooling the CPU', 'Backing up data', 'Compressing files'], d: 'easy' },
  { q: 'What is cloud storage?', a: 'Files kept on remote servers', pool: ['Files kept on your device', 'Deleted files', 'Compressed files'], d: 'easy' },
  { q: 'What does "backup" mean?', a: 'Keeping a spare copy of data', pool: ['Deleting old data', 'Compressing data', 'Encrypting data'], d: 'easy' },
  { q: 'What does an operating system do?', a: 'Manages hardware and programs', pool: ['Browses the web only', 'Edits documents', 'Plays music'], d: 'medium' },
  { q: 'What is open-source software?', a: 'Software whose source code is public', pool: ['Software that is always free', 'Software with no licence', 'Software without bugs'], d: 'medium' },
  { q: 'What is a bug in software?', a: 'An error causing wrong behaviour', pool: ['A security feature', 'A type of virus', 'A hardware fault'], d: 'medium' },
  { q: 'What is an API?', a: 'A defined way for programs to talk to each other', pool: ['A type of database', 'A programming language', 'A network cable'], d: 'medium' },
  { q: 'What is a server?', a: 'A computer that provides services to others', pool: ['A personal laptop', 'A network cable', 'A storage disk'], d: 'medium' },
  { q: 'What does HTTPS add over HTTP?', a: 'Encryption', pool: ['Speed', 'Compression', 'Caching'], d: 'medium' },
  { q: 'What is a domain name?', a: 'A human-readable address for a website', pool: ['A server’s brand', 'An email password', 'A file format'], d: 'medium' },
  { q: 'What does DNS do?', a: 'Turns domain names into IP addresses', pool: ['Encrypts traffic', 'Stores websites', 'Blocks adverts'], d: 'medium' },
  { q: 'What is bandwidth?', a: 'How much data can be transferred per second', pool: ['The delay before transfer', 'The number of users', 'The size of a file'], d: 'medium' },
  { q: 'What is a compiler?', a: 'A tool that turns source code into machine code', pool: ['A tool that runs tests', 'A text editor', 'A debugger'], d: 'medium' },
  { q: 'What is a variable in programming?', a: 'A named place to store a value', pool: ['A fixed constant', 'A function call', 'A comment'], d: 'medium' },
  { q: 'What is a loop in programming?', a: 'Code that repeats', pool: ['Code that runs once', 'A syntax error', 'A data type'], d: 'medium' },
  { q: 'What is a function in programming?', a: 'A reusable block of code', pool: ['A stored value', 'A file format', 'A network call'], d: 'medium' },
  { q: 'What does "debugging" mean?', a: 'Finding and fixing errors', pool: ['Writing documentation', 'Deploying code', 'Compressing files'], d: 'medium' },
  { q: 'What is a repository in version control?', a: 'A store of a project and its history', pool: ['A running server', 'A build output', 'A test suite'], d: 'medium' },
  { q: 'What is phishing?', a: 'Tricking people into revealing credentials', pool: ['Scanning for open ports', 'Overloading a server', 'Cracking encryption'], d: 'medium' },
  { q: 'What is a VPN mainly used for?', a: 'Sending traffic through an encrypted tunnel', pool: ['Speeding up downloads', 'Blocking adverts', 'Storing passwords'], d: 'medium' },
  { q: 'What is a cookie in a web browser?', a: 'A small file storing site data', pool: ['A cached image', 'A downloaded program', 'A browser plugin'], d: 'medium' },
  { q: 'What does "responsive design" mean?', a: 'A layout that adapts to screen size', pool: ['A fast-loading site', 'A site with animations', 'A site with no images'], d: 'medium' },
  { q: 'What is a bit?', a: 'A single binary digit', pool: ['Eight bytes', 'A kilobyte', 'A pixel'], d: 'medium' },
  { q: 'How many bits are in a byte?', a: 'Eight', pool: ['Four', 'Sixteen', 'Ten'], d: 'medium' },
  { q: 'What number system do computers use internally?', a: 'Binary', pool: ['Decimal', 'Hexadecimal only', 'Octal'], d: 'medium' },
  { q: 'What does "open a port" mean on a server?', a: 'Allowing network connections on a number', pool: ['Adding disk space', 'Rebooting the machine', 'Installing software'], d: 'medium' },
  { q: 'What is a container in software deployment?', a: 'A packaged app with its dependencies', pool: ['A physical server', 'A database table', 'A backup archive'], d: 'medium' },
  { q: 'What is refactoring?', a: 'Improving code structure without changing behaviour', pool: ['Adding new features', 'Fixing a security hole', 'Rewriting in a new language'], d: 'medium' },
];

export const FOOD_FACTS2: F[] = [
  { q: 'Which vegetable makes people cry when cut?', a: 'Onion', pool: ['Carrot', 'Potato', 'Cabbage'], d: 'easy' },
  { q: 'What is the main ingredient in bread?', a: 'Flour', pool: ['Sugar', 'Butter', 'Milk'], d: 'easy' },
  { q: 'What is the main ingredient in an omelette?', a: 'Eggs', pool: ['Milk', 'Cheese', 'Flour'], d: 'easy' },
  { q: 'Which fruit is yellow and peeled before eating?', a: 'Banana', pool: ['Apple', 'Grape', 'Cherry'], d: 'easy' },
  { q: 'What drink comes from coffee beans?', a: 'Coffee', pool: ['Tea', 'Cocoa', 'Cider'], d: 'easy' },
  { q: 'Which spice is the most expensive by weight?', a: 'Saffron', pool: ['Vanilla', 'Cardamom', 'Cinnamon'], d: 'medium' },
  { q: 'Which food is made by bees?', a: 'Honey', pool: ['Syrup', 'Molasses', 'Nectar'], d: 'easy' },
  { q: 'What is milk from cows used to make?', a: 'Cheese', pool: ['Bread', 'Rice', 'Pasta'], d: 'easy' },
  { q: 'What is the base of a pizza?', a: 'Dough', pool: ['Rice', 'Pastry', 'Batter'], d: 'easy' },
  { q: 'What is guacamole made from?', a: 'Avocado', pool: ['Peas', 'Courgette', 'Spinach'], d: 'easy' },
  { q: 'What is the main ingredient in chips or fries?', a: 'Potato', pool: ['Corn', 'Cassava', 'Turnip'], d: 'easy' },
  { q: 'Which drink is made from tea leaves?', a: 'Tea', pool: ['Coffee', 'Cocoa', 'Juice'], d: 'easy' },
  { q: 'What is popcorn made from?', a: 'Corn', pool: ['Rice', 'Wheat', 'Barley'], d: 'easy' },
  { q: 'What flavour is vanilla?', a: 'Sweet and floral', pool: ['Sour and sharp', 'Bitter and smoky', 'Salty and savoury'], d: 'easy' },
  { q: 'Which fruit has seeds on the outside?', a: 'Strawberry', pool: ['Blueberry', 'Raspberry', 'Cherry'], d: 'easy' },
  { q: 'What is tofu made from?', a: 'Soybeans', pool: ['Chickpeas', 'Rice', 'Wheat'], d: 'easy' },
  { q: 'What is the main ingredient in chocolate?', a: 'Cocoa', pool: ['Coffee', 'Carob', 'Vanilla'], d: 'easy' },
  { q: 'What is a food that comes from a hen?', a: 'An egg', pool: ['Milk', 'Honey', 'Cheese'], d: 'easy' },
  { q: 'Which of these is a citrus fruit?', a: 'Lemon', pool: ['Peach', 'Plum', 'Pear'], d: 'easy' },
  { q: 'What is dough kneaded for?', a: 'To develop gluten', pool: ['To cool it', 'To add sugar', 'To remove water'], d: 'medium' },
  { q: 'What does "al dente" mean for pasta?', a: 'Firm to the bite', pool: ['Very soft', 'Overcooked', 'Raw'], d: 'medium' },
  { q: 'What is blanching?', a: 'Briefly boiling then cooling in ice water', pool: ['Slow roasting', 'Deep frying', 'Marinating'], d: 'medium' },
  { q: 'What is sautéing?', a: 'Cooking quickly in a little fat over high heat', pool: ['Boiling in water', 'Cooking in an oven', 'Steaming over water'], d: 'medium' },
  { q: 'What is braising?', a: 'Searing then slow-cooking in liquid', pool: ['Grilling over flame', 'Deep frying', 'Cooking in a microwave'], d: 'medium' },
  { q: 'What is poaching?', a: 'Cooking gently in barely simmering liquid', pool: ['Cooking over dry heat', 'Cooking in hot fat', 'Cooking under a grill'], d: 'medium' },
  { q: 'What is the Maillard reaction responsible for?', a: 'Browning and savoury flavour', pool: ['Sweetness in fruit', 'Sourness in yoghurt', 'Bitterness in coffee'], d: 'medium' },
  { q: 'What is caramelisation?', a: 'Sugar browning under heat', pool: ['Protein setting', 'Fat separating', 'Starch dissolving'], d: 'medium' },
  { q: 'What does "searing" meat do?', a: 'Browns the surface for flavour', pool: ['Seals in all juices', 'Cooks it through', 'Tenderises it'], d: 'medium' },
  { q: 'What does resting meat after cooking achieve?', a: 'Juices redistribute', pool: ['It cools completely', 'It cooks further only', 'It absorbs salt'], d: 'medium' },
  { q: 'What is a marinade mainly for?', a: 'Adding flavour before cooking', pool: ['Preserving indefinitely', 'Sterilising the meat', 'Removing fat'], d: 'medium' },
  { q: 'What is emulsification?', a: 'Combining two liquids that do not normally mix', pool: ['Boiling off water', 'Separating fat', 'Fermenting sugar'], d: 'medium' },
  { q: 'Which sauce is a classic emulsion of egg yolk and oil?', a: 'Mayonnaise', pool: ['Ketchup', 'Soy sauce', 'Vinaigrette'], d: 'medium' },
  { q: 'What does yeast consume to make bread rise?', a: 'Sugar', pool: ['Salt', 'Fat', 'Water'], d: 'medium' },
  { q: 'What does salt do to meat when brined?', a: 'Helps it retain moisture', pool: ['Dries it out', 'Adds fat', 'Removes protein'], d: 'medium' },
  { q: 'Which fat has the highest smoke point of these?', a: 'Refined sunflower oil', pool: ['Butter', 'Extra virgin olive oil', 'Lard'], d: 'medium' },
  { q: 'What is fermentation?', a: 'Microbes converting sugars into acids or alcohol', pool: ['Heating to kill bacteria', 'Freezing to preserve', 'Drying to remove water'], d: 'medium' },
  { q: 'Which food is produced by fermenting milk?', a: 'Yoghurt', pool: ['Cream', 'Butter', 'Condensed milk'], d: 'medium' },
  { q: 'What is pasteurisation for?', a: 'Killing harmful microbes with heat', pool: ['Adding vitamins', 'Thickening liquid', 'Removing fat'], d: 'medium' },
  { q: 'What does "mise en place" mean?', a: 'Everything prepared and in position', pool: ['Cooking in one pan', 'Plating the dish', 'Cleaning as you go'], d: 'medium' },
  { q: 'What is a bain-marie?', a: 'A water bath for gentle heating', pool: ['A pastry brush', 'A type of oven', 'A chopping technique'], d: 'medium' },
  { q: 'What is a chiffonade?', a: 'Leaves sliced into thin ribbons', pool: ['Cubed vegetables', 'Grated cheese', 'Minced garlic'], d: 'medium' },
  { q: 'What is a julienne cut?', a: 'Thin matchstick strips', pool: ['Fine dice', 'Thick rounds', 'Rough chop'], d: 'medium' },
  { q: 'What is stock made from?', a: 'Simmered bones and vegetables', pool: ['Cream and flour', 'Wine and butter', 'Juice and herbs'], d: 'medium' },
  { q: 'What is a reduction?', a: 'A liquid simmered to concentrate flavour', pool: ['A thinned sauce', 'A chilled soup', 'A whipped cream'], d: 'medium' },
  { q: 'Why do recipes say to preheat the oven?', a: 'So food cooks at the right temperature from the start', pool: ['To save electricity', 'To clean the oven', 'To dry the air'], d: 'medium' },
  { q: 'What is tempering chocolate for?', a: 'A glossy finish and firm snap', pool: ['Making it sweeter', 'Removing cocoa butter', 'Speeding melting'], d: 'hard' },
  { q: 'What is sous vide?', a: 'Cooking sealed food in precisely heated water', pool: ['Cooking over open flame', 'Cooking under pressure', 'Cooking in hot oil'], d: 'hard' },
  { q: 'What is umami?', a: 'A savoury fifth basic taste', pool: ['A type of spice', 'A cooking method', 'A Japanese dish'], d: 'hard' },
  { q: 'What is gluten?', a: 'A protein network formed in wheat dough', pool: ['A type of sugar', 'A fat in dairy', 'A starch in rice'], d: 'hard' },
  { q: 'What is a "mother sauce" in French cuisine?', a: 'A base sauce others are built from', pool: ['A dessert sauce', 'A cold sauce', 'A regional speciality'], d: 'hard' },
  { q: 'What is confit?', a: 'Food slowly cooked and preserved in fat', pool: ['Food cured in salt', 'Food smoked over wood', 'Food pickled in vinegar'], d: 'hard' },
];

export const POP_FACTS2: F[] = [
  { q: 'How many strings does a standard guitar have?', a: 'Six', pool: ['Four', 'Five', 'Seven'], d: 'easy' },
  { q: 'How many keys does a standard piano have?', a: '88', pool: ['66', '76', '99'], d: 'medium' },
  { q: 'Which instrument has black and white keys?', a: 'The piano', pool: ['The violin', 'The flute', 'The drum'], d: 'easy' },
  { q: 'How many lines are in a musical staff?', a: 'Five', pool: ['Four', 'Six', 'Three'], d: 'medium' },
  { q: 'Which instrument is played with a bow?', a: 'The violin', pool: ['The trumpet', 'The clarinet', 'The piano'], d: 'easy' },
  { q: 'What do you call a group of singers performing together?', a: 'A choir', pool: ['An orchestra', 'A band', 'An ensemble of instruments'], d: 'easy' },
  { q: 'Who leads an orchestra?', a: 'The conductor', pool: ['The composer', 'The soloist', 'The producer'], d: 'easy' },
  { q: 'What is a solo performance by one person?', a: 'A solo', pool: ['A duet', 'A trio', 'A quartet'], d: 'easy' },
  { q: 'How many people are in a duet?', a: 'Two', pool: ['One', 'Three', 'Four'], d: 'easy' },
  { q: 'How many people are in a trio?', a: 'Three', pool: ['Two', 'Four', 'Five'], d: 'easy' },
  { q: 'Which instrument is a member of the percussion family?', a: 'The drum', pool: ['The flute', 'The cello', 'The trumpet'], d: 'easy' },
  { q: 'What is a play performed entirely in song called?', a: 'An opera', pool: ['A ballet', 'A concerto', 'A symphony'], d: 'easy' },
  { q: 'What is a dance performance with no words called?', a: 'A ballet', pool: ['An opera', 'A musical', 'A recital'], d: 'easy' },
  { q: 'What is a long piece for full orchestra called?', a: 'A symphony', pool: ['A sonata', 'A fugue', 'An etude'], d: 'medium' },
  { q: 'Where do actors perform in a theatre?', a: 'On the stage', pool: ['In the stalls', 'In the wings only', 'In the gallery'], d: 'easy' },
  { q: 'What are an actor’s spoken words called?', a: 'Lines', pool: ['Cues', 'Props', 'Scores'], d: 'easy' },
  { q: 'What is an object used by an actor on stage?', a: 'A prop', pool: ['A cue', 'A set', 'A score'], d: 'easy' },
  { q: 'What is the written text of a film called?', a: 'The screenplay', pool: ['The score', 'The storyboard', 'The synopsis'], d: 'easy' },
  { q: 'Who directs a film?', a: 'The director', pool: ['The producer', 'The editor', 'The writer'], d: 'easy' },
  { q: 'What is the music written for a film called?', a: 'The soundtrack', pool: ['The dialogue', 'The dub', 'The mix'], d: 'easy' },
  { q: 'What is a very short film advert for a movie called?', a: 'A trailer', pool: ['A teaser reel', 'A montage', 'A credit roll'], d: 'easy' },
  { q: 'What are the names listed at the end of a film?', a: 'The credits', pool: ['The captions', 'The titles only', 'The index'], d: 'easy' },
  { q: 'What is a painting of a person called?', a: 'A portrait', pool: ['A landscape', 'A still life', 'An abstract'], d: 'easy' },
  { q: 'What is a painting of the countryside called?', a: 'A landscape', pool: ['A portrait', 'A still life', 'A mural'], d: 'easy' },
  { q: 'What is a painting of objects like fruit called?', a: 'A still life', pool: ['A portrait', 'A landscape', 'A seascape'], d: 'easy' },
  { q: 'What is a large painting on a wall called?', a: 'A mural', pool: ['A fresco only', 'A canvas', 'A collage'], d: 'easy' },
  { q: 'What are the three primary colours in paint?', a: 'Red, yellow and blue', pool: ['Red, green and blue', 'Cyan, magenta and yellow', 'Orange, green and purple'], d: 'easy' },
  { q: 'What colour do you get mixing blue and yellow?', a: 'Green', pool: ['Purple', 'Orange', 'Brown'], d: 'easy' },
  { q: 'What is sculpture usually made from?', a: 'Solid materials like stone or metal', pool: ['Paint on canvas', 'Digital files', 'Fabric only'], d: 'easy' },
  { q: 'What is the front cover text of a book called?', a: 'The title', pool: ['The blurb', 'The index', 'The preface'], d: 'easy' },
  { q: 'What is a made-up story called?', a: 'Fiction', pool: ['Non-fiction', 'A biography', 'A memoir'], d: 'easy' },
  { q: 'What is a true account of someone’s life by another person?', a: 'A biography', pool: ['An autobiography', 'A novel', 'An essay'], d: 'easy' },
  { q: 'What is a short story in verse form called?', a: 'A poem', pool: ['A novel', 'A play', 'An essay'], d: 'easy' },
  { q: 'What are the divisions of a book called?', a: 'Chapters', pool: ['Verses', 'Acts', 'Scenes'], d: 'easy' },
  { q: 'What are the divisions of a play called?', a: 'Acts', pool: ['Chapters', 'Stanzas', 'Volumes'], d: 'easy' },
  { q: 'What is a group of lines in a poem called?', a: 'A stanza', pool: ['A chapter', 'A scene', 'A paragraph'], d: 'medium' },
  { q: 'What is a 14-line poem called?', a: 'A sonnet', pool: ['A haiku', 'An ode', 'An elegy'], d: 'medium' },
  { q: 'How many lines does a haiku have?', a: 'Three', pool: ['Four', 'Five', 'Seven'], d: 'medium' },
  { q: 'What is a comparison using "like" or "as"?', a: 'A simile', pool: ['A metaphor', 'An analogy', 'A hyperbole'], d: 'medium' },
  { q: 'What is a direct comparison without "like" or "as"?', a: 'A metaphor', pool: ['A simile', 'An idiom', 'A pun'], d: 'medium' },
  { q: 'What is deliberate exaggeration called?', a: 'Hyperbole', pool: ['Irony', 'Satire', 'Allegory'], d: 'medium' },
  { q: 'What is giving human traits to objects called?', a: 'Personification', pool: ['Alliteration', 'Onomatopoeia', 'Assonance'], d: 'medium' },
  { q: 'What is repeating the same starting sound called?', a: 'Alliteration', pool: ['Assonance', 'Rhyme', 'Metre'], d: 'medium' },
  { q: 'What is a word that sounds like its meaning?', a: 'Onomatopoeia', pool: ['Alliteration', 'Metaphor', 'Euphemism'], d: 'medium' },
  { q: 'What is the main character of a story called?', a: 'The protagonist', pool: ['The antagonist', 'The narrator', 'The author'], d: 'medium' },
  { q: 'What is the character opposing the hero called?', a: 'The antagonist', pool: ['The protagonist', 'The narrator', 'The foil'], d: 'medium' },
  { q: 'What is the turning point of a story called?', a: 'The climax', pool: ['The exposition', 'The resolution', 'The prologue'], d: 'medium' },
  { q: 'What is the setup at the start of a story called?', a: 'The exposition', pool: ['The climax', 'The denouement', 'The epilogue'], d: 'medium' },
  { q: 'What is a hint of what is to come called?', a: 'Foreshadowing', pool: ['Flashback', 'Symbolism', 'Irony'], d: 'medium' },
  { q: 'What is a scene set in the past called?', a: 'A flashback', pool: ['A flash-forward', 'A montage', 'A prologue'], d: 'medium' },
  { q: 'What is the perspective a story is told from called?', a: 'Point of view', pool: ['The theme', 'The tone', 'The setting'], d: 'medium' },
  { q: 'What is the underlying message of a story called?', a: 'The theme', pool: ['The plot', 'The setting', 'The genre'], d: 'medium' },
];

export const BIO_FACTS2: F[] = [
  { q: 'How many hearts does an octopus have?', a: 'Three', pool: ['One', 'Two', 'Four'], d: 'medium' },
  { q: 'What do caterpillars turn into?', a: 'Butterflies or moths', pool: ['Beetles', 'Bees', 'Dragonflies'], d: 'easy' },
  { q: 'Which animal is known for its long neck?', a: 'The giraffe', pool: ['The zebra', 'The rhino', 'The camel'], d: 'easy' },
  { q: 'What do we call animals with a backbone?', a: 'Vertebrates', pool: ['Invertebrates', 'Arthropods', 'Molluscs'], d: 'easy' },
  { q: 'What is the largest animal on Earth?', a: 'The blue whale', pool: ['The elephant', 'The giraffe', 'The whale shark'], d: 'easy' },
  { q: 'Which body part pumps blood?', a: 'The heart', pool: ['The lungs', 'The liver', 'The kidney'], d: 'easy' },
  { q: 'How many bones does an adult human have, roughly?', a: 'About 206', pool: ['About 150', 'About 300', 'About 500'], d: 'medium' },
  { q: 'Which organ filters waste from blood?', a: 'The kidney', pool: ['The stomach', 'The lung', 'The spleen'], d: 'medium' },
  { q: 'What are the tiny air sacs in the lungs called?', a: 'Alveoli', pool: ['Villi', 'Nephrons', 'Follicles'], d: 'medium' },
  { q: 'What do we call the process of cells dividing in two?', a: 'Mitosis', pool: ['Meiosis', 'Osmosis', 'Diffusion'], d: 'medium' },
  { q: 'What is DNA short for?', a: 'Deoxyribonucleic acid', pool: ['Dinucleic acid', 'Dual nuclear acid', 'Deoxyribose amine'], d: 'medium' },
  { q: 'How many chromosomes do humans normally have?', a: '46', pool: ['23', '48', '44'], d: 'medium' },
  { q: 'Which vitamin does sunlight help the body make?', a: 'Vitamin D', pool: ['Vitamin C', 'Vitamin A', 'Vitamin B12'], d: 'easy' },
  { q: 'What is the largest organ of the human body?', a: 'The skin', pool: ['The liver', 'The brain', 'The intestine'], d: 'easy' },
  { q: 'Which cells carry oxygen in blood?', a: 'Red blood cells', pool: ['White blood cells', 'Platelets', 'Plasma cells'], d: 'easy' },
  { q: 'Which cells fight infection?', a: 'White blood cells', pool: ['Red blood cells', 'Platelets', 'Nerve cells'], d: 'easy' },
  { q: 'What gas do plants release during photosynthesis?', a: 'Oxygen', pool: ['Carbon dioxide', 'Nitrogen', 'Methane'], d: 'easy' },
  { q: 'What green pigment do plants use to capture light?', a: 'Chlorophyll', pool: ['Melanin', 'Carotene', 'Haemoglobin'], d: 'medium' },
];
